### ISSUE TITLE
Weather location 

### ISSUE THREAD

**Issue by mirko-wq** [mzeryck/Weather-Cal#100]
Since the update at Tuesday, 
the weather location is not updating.
I try a new api and the open weather locate “de”
and a zip code or “blank” device’s locate
without success.

**Comment by icsAT** [comment]
@mirko-wq
there is a new parameter "Location update frequency" in the "Overall settings". Maybe you check if this effects your expected behavior.

"de" as value for "OpenWeather locale" should be fine.
As "Local code" you should use "de_DE" or nothing. But this should not effect your weather. 


Greetings Andre

**Comment by mirko-wq** [comment]
@icsAT 
Thank you for reply! 
I try different times for the "Location update frequency" from 5 minutes .. to 60 minutes ..
Without success.
Another script is using the gps from my device.
So it looks that the gps for Scriptable is working.

**Comment by mirko-wq** [comment]
I deleted the weather call code and made a complete reset. It’s a little bit strange. It still shows the location i visit on Thursday.

**Comment by icsAT** [comment]
what kind of reset? did you mean a reboot of your device or the reset functionality from the script.

**Comment by icsAT** [comment]
After a quick glance into the code I would think the cache is not deleted, no matter what you did. That might explain, where the wrong location come from, but not why it's not refreshing.

**Comment by mirko-wq** [comment]
“Completely reset widget”
That don’t work.

I reinstalled the scriptable app. After that I start a new weather call script. It starts from beginning. Now the location is working!

**Comment by icsAT** [comment]
Glad to hear it worked. Leave the issue open, so that Max could have a look at it.

@mzeryck could you check if I am right and the cache files are not deleted when using the "Completely reset widget" function. I think thy should, except the API Key maybe.

Greetings André

**Comment by LTLNEMO** [comment]
Noticed this all well yesterday. Gonna try the troubleshooting steps

**Comment by LTLNEMO** [comment]
Reinstall of Scriptable works but doesn't update location again after that.  Have to keep deleting and installing for new location

**Comment by mzeryck** [comment]
Thanks all - I will take a look at it this week! Unfortunately I am based in the US where changing locations is not ideal, but I'll try and see if I can find the bugs in the caching code (which is new).

**Comment by mzeryck** [comment]
@LTLNEMO @mirko-wq @icsAT Thanks all - and sorry for taking a longer break than I anticipated. I believe the most recent commit fixes the location caching bug: now, you can use 0 for the update frequency to always update your location, and to lock your location you can enter -1. Also, the reset function should clear all cache files now! Please let me know if there are additional issues.

**Comment by icsAT** [comment]
@mzeryck thanks for the update. Looks like location is updating fine to me. Merry Christmas to you and thanks again for your excellent work and widget. Enjoy the holidays. 

Greetings from Germany

Andre
