### ISSUE TITLE
Widget doesn’t to update informations automatically

### ISSUE THREAD

**Issue by jbastruz** [mzeryck/Weather-Cal#102]
Hi, the widget doesn't to update informations automatically, I am have to run the script manually, there is a tip to fix this point?

**Comment by icsAT** [comment]
@jbastruz wich part of the widget is not updating?

The update frequency of the widget is somehow up to iOS, depending on how often you look at it, as far as I know.
Also some of the item's are cached for some time, so they would not update any second anyway.

But, as you see on issue #100 there are more people haveing a problem with the update of their location.

**Comment by deroverda** [comment]
Update to latest code and reboot/restart your phone. I've read widgets refreshes every 6-11 min. There's also a scriptable refresh widgets shortcut that you could try.

**Comment by mzeryck** [comment]
@jbastruz @icsAT @deroverda I believe there was a bug in the cache code, which should now be fixed. Leaving this issue open in case there are any remaining issues.
