### ISSUE TITLE
Changing Color of the ConditionSymbol

### ISSUE THREAD

**Issue by anonym6373** [mzeryck/Weather-Cal#103]
Hey there, 
I want the Widget to have a White background, but if I change the solid color to #ffffff I’m not able to see the ConditionSymbol any more if it‘s anything  with clouds or sth like that.
Now I want to change the color of the Condition Symbol („clouds.fill“) to gray or another color, which isn’t white. Please help me with this.
![09D5497B-50BF-4FD5-86D5-89896056D8E0](https://user-images.githubusercontent.com/74816014/102818023-200ed180-43d1-11eb-8f94-110536ed5103.png)

**Comment by icsAT** [comment]
@anonym6373 first of all you need to set "Icons match text color" to "true" in the "Overall settings". Then you are able to set the condition icon with the text color. F.e. color of "Large temperature label" for the icon and text in your screenshot.

**Comment by anonym6373** [comment]
Ok, nur is is possible to change the Color of the Symbol without changing the color of the title? I mean to change the color of separate SFSymbols in the Widget Code(like „Clouds.rain.fill“ in blue, and „Sun.max.fill“ in yellow).

**Comment by icsAT** [comment]
@anonym6373 usually the sun is yellow by default and clouds are kind of white. There is no posibillity to change that as far as I know besides giving them the color of the corresponding text. In issue #75 there is a request in sizing the icons as a future feature. Maybe @mzeryck could have a look if he could include your request too, once he works on that point. Unfortunately I don't see any possibility out of the box at the moment.

**Comment by mzeryck** [comment]
@anonym6373 @icsAT Unfortunately, there isn't a good way to do this - there are so many possible symbol and color combinations. The existing options (use the iOS default vs. match the color of the text) cover most situations pretty well. What I really wish is that the SFSymbol object could specify the "base color" so it looks correct with a light or dark background, but this isn't possible. Sorry about that!
