### ISSUE TITLE
2020-12-26 23:17:13: Error on line 715:83: TypeError: null is not an object (evaluating 'event.calendar.identifier')

### ISSUE THREAD

**Issue by jigadijac** [mzeryck/Weather-Cal#108]
Hi I get this error. How do I rectify it?

**Comment by LTLNEMO** [comment]
Try all troubleshooting.  Meaning Update code.  If not that. Delete Weather Cal and Weather Cal Code and re-add script and rerun. If not that then reinstall scriptable. Generally fixes every issue
