### ISSUE TITLE
What should i do

### ISSUE THREAD

**Issue by benedictusaldogithub** [mzeryck/Weather-Cal#11]
So when i paste the text from the web and i run the script, the notification that show up is like this. (I already put the API from the weather website that you told).
![image](https://user-images.githubusercontent.com/73035416/96349797-1f5d7480-10dc-11eb-8c34-e53e1c290c1f.png)
![image](https://user-images.githubusercontent.com/73035416/96349802-25ebec00-10dc-11eb-96a6-6c6b5c3d9d8f.png)

**Comment by mzeryck** [comment]
That is very odd! Does the top of the script look like this: `apiKey = "abcdefg"` ?

**Comment by benedictusaldogithub** [comment]
Yap, i enter the apikey exact same the web you provide

**Comment by mzeryck** [comment]
Did you allow location access for the Scriptable app? You can check by going to Settings > Scriptable > Location.

**Comment by mzeryck** [comment]
I'm closing this issue, as I'm guessing the solution I suggested above worked.
