### ISSUE TITLE
The news feature doesn't seem to work

### ISSUE THREAD

**Issue by ArnavMotwani** [mzeryck/Weather-Cal#110]
In the widget preferences there is a News section where I entered the following RSS feed `https://www.theverge.com/rss/index.xml`

This just seems to leave a gap in the widget. Here is my layout 

```
row
  column
    date
    sunset
    space

  column(90)
    current
      space
row
  column
    events
  column
    reminders
row
  news
```

**Comment by LTLNEMO** [comment]
@ArnavMotwani 
I'm guessing you just forgot to set column>news after row. But I can confirm news item isn't working

**Comment by ArnavMotwani** [comment]
@LTLNEMO Even with a column  
doesn't work, I think that it is one feature I am eager to see

**Comment by LTLNEMO** [comment]
It just started working for me

**Comment by ArnavMotwani** [comment]
@LTLNEMO Do you mind sharing your layout?

**Comment by ArnavMotwani** [comment]
@LTLNEMO Nevermind it's working for me too now
