### ISSUE TITLE
Widgets won’t export properly

### ISSUE THREAD

**Issue by ArnavMotwani** [mzeryck/Weather-Cal#115]
Whether you export as text or a file, it doesn't work you get the error `Error on line 15: SyntaxError Unexpected string literal ",". Expected ')' to end argument list.` if you export to files and `Error on line 26: SyntaxError Unexpected string literal ",". Expected ')' to end argument list.` if you export to text.

**Comment by mzeryck** [comment]
@ArnavMotwani I know you submitted this a year ago, but wondering if you are still using Weather Cal - if so, I would be happy to look into the issue if you're willing to share your Weather Cal files.

**Comment by ArnavMotwani** [comment]
Its been a while, ill take a look at whether I still have my files and whether this is still an issue. Ill reopen this issue if I do.
