### ISSUE TITLE
Hourly weather offsets are wrong?

### ISSUE THREAD

**Issue by mrJudahBella** [mzeryck/Weather-Cal#116]
Hello there! I recently stumbled on Scriptable and Weather Cal and I'm in the process of customising it. I noticed that for the hourly forecast, while comparing to the OpenWeather app, the time does not seem to align—it seems to be off by an hour. I've attached screenshots to better describe what I mean:

![IMG_0906](https://user-images.githubusercontent.com/68019824/104261566-c6c22b80-54c0-11eb-9750-c70f1f09d916.PNG)
![IMG_0905](https://user-images.githubusercontent.com/68019824/104261578-ce81d000-54c0-11eb-8ba3-efdb9bb635c6.PNG)

It just seems like the weather data needs to be shifted left by an hour to be correct. Hopefully someone can fix this!

**Comment by mzeryck** [comment]
@mrJudahBella I know it's been a long time since you submitted this, but just wanted to say thank you for reporting it - I took a break from this project for a while. Luckily it was an easy fix.

**Comment by mrJudahBella** [comment]
Thanks for the fix! Hope you're doing well.
