### ISSUE TITLE
Error on line 753:51: TypeError: undefined is not an object (evaluating 'weatherDataRaw.current.temp')

### ISSUE THREAD

**Issue by Goldsucher** [mzeryck/Weather-Cal#12]
I tried to run the script and get the error mentioned above. I'm pretty sure, it's not due to the api key, because the same key works in other applications.

**Comment by Adrian-Grimm** [comment]
I had the same error. In my case it was the API key. If it is a new one it takes some time..

**Comment by italoboy** [comment]
It doesn't work after new API and 24 hours.

**Comment by mzeryck** [comment]
There is a caching issue - where if the API call fails, it still stores the value. But it shouldn't persist. Is the entire script unmodified besides the API key?

**Comment by italoboy** [comment]
I doesn't run without fixing this error, you better add city ID as well.

**Comment by mzeryck** [comment]
Can you tell me what your `locale` value is? For example, mine is `let locale = "en"`

**Comment by italoboy** [comment]
> Can you tell me what your `locale` value is? For example, mine is `let locale = "en"`

It is the same. I didn't change it.

**Comment by Goldsucher** [comment]
yes still the same error here. Wouldn't it be easier to set the location in the code?

**Comment by mzeryck** [comment]
Another question - is location access enabled for Scriptable? You can check by going to Settings > Scriptable > Location.

**Comment by Goldsucher** [comment]
okay that was the problem. Enabling the location access fixed it. But I would appreciate the possibility to set the location in the code and run the script without location access

**Comment by mzeryck** [comment]
You can hard-code the location by deleting and replacing the entire `setupLocation()` function (it starts around line 660) and replacing it with the following code:
```
// Set up the locationData object.
async function setupLocation() {
  locationData = {
    latitude: 37.332280,
    longitude: -122.010980,
    locality: "Cupertino"
  }
}
```
Of course, you'll need to use a site [like this](https://www.latlong.net) to find your latitude and longitude, and replace "Cupertino" with your city/town name.
