### ISSUE TITLE
2021-01-24 11:38:20: Error on line 1635:29: SyntaxError: JSON Parse error: Unexpected EOF

### ISSUE THREAD

**Issue by ryansowinski** [mzeryck/Weather-Cal#120]
How do I fix this? I tried updating the code.
![9B81F7B7-2C22-4D40-9AA1-58F8DA8E0060](https://user-images.githubusercontent.com/77933856/105638665-77bdb400-5e39-11eb-91e8-7de1d2befbd9.jpeg)

**Comment by MatthiasSeifert1** [comment]
Same

**Comment by icsAT** [comment]
If you have the recent code and you did not change a thing the problem might has to do something with reading the cache.
You could try to set up the widget as a new Scriptable script with a different name.

**Comment by ryansowinski** [comment]
Did not work

**Comment by MatthiasSeifert1** [comment]
Did not work.

Here the error is only on iPad. Same code on iPhone works.

**Comment by mzeryck** [comment]
Closing this issue because it seems to be the same as #137 - so will be updating there.
