### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Stahl80** [mzeryck/Weather-Cal#121]
Suddenly changing color codes don’t have any effect. 
Had some but all text is now showing in white. 
Editing the codes or changing them have no effect. 

Ex:
greeting:    { size: 30, color: "71AC9E", font: "semibold" },
    eventLabel:  { size: 14, color: "", font: "semibold" },
    eventTitle:  { size: 14, color: "", font: "semibold" },
    eventTime:   { size: 14, color: "ffffffcc", font: "" },
    noEvents:    { size: 30, color: "", font: "semibold" },

**Comment by musmer** [comment]
I had the same issue few weeks ago. Check if you have a value in default font settings.

**Comment by adamengineering** [comment]
Check the Widget Setup and go to the Edit preferences section. Herein setup your values as you want them to be. Enter the color code and do the same also for dark mode, otherwise if your device is in dark mode, it will show up 'all white'.
