### ISSUE TITLE
Can't access "Text sizes, colors, and fonts" settings while all other settings work. 

### ISSUE THREAD

**Issue by deroverda** [mzeryck/Weather-Cal#122]
This started like a week ago. Only thing I remember doing is messing around with the layout of the widgets items (week, battery, date etc.). 

When I press "edit preferences" and try to access the "Text sizes ..." menu it won't work. All other settings work, but not this. Does anyone know how to fix this? Tried deleting the code so it auto-updates, restarted the phone, force-shutdown the app etc. Nothing works. 

Thanks in advance.

**Comment by icsAT** [comment]
Did you try to set up a new widget with a different name or reset the Widget with "Other settings" and "Completely reset widget".

**Comment by deroverda** [comment]
> Did you try to set up a new widget with a different name or reset the Widget with "Other settings" and "Completely reset widget".

I ended up starting off from scratch and creating a new script and the problem is now solved. Thanks for responding though.
