### ISSUE TITLE
Calendar events don’t show

### ISSUE THREAD

**Issue by bckelley** [mzeryck/Weather-Cal#123]
![image](https://user-images.githubusercontent.com/15696431/105853819-5a0c5e00-5fa3-11eb-9297-2c5b84cf2c9f.png)
![image](https://user-images.githubusercontent.com/15696431/105853834-5d074e80-5fa3-11eb-80ce-186dd435cf7c.png)

Any help before I delete

**Comment by adamengineering** [comment]
Have you tried using only one calendar to be shown? Maybe one of them contains a value that is interacting with the correct readout...

**Comment by rulerofthenight** [comment]
Same issue. Just 1 calendar selected and nothing shows on the widget

**Comment by rulerofthenight** [comment]
Any suggestion?

**Comment by icsAT** [comment]
Show all day events is turned off on your Screenshot. Since there are Calendars selected like Birthday and Holidays, that part could not work, but normal events should show up.

**Comment by rulerofthenight** [comment]
I have all day events turned on, and tried multiple calendars, one by one.
Not working here

**Comment by rulerofthenight** [comment]
Solved. It was the "future days shown at hour" setting.
I set 0 as value and events showed up.
