### ISSUE TITLE
Hello, I would like to consult how to expand the scope of calendar events.

### ISSUE THREAD

**Issue by Aellus** [mzeryck/Weather-Cal#135]
hello，The code shows this. . “Set to 0 to show today's events only. The maximum is 7."
I want to expand the scope of events, not just this week and next week.    
Line 744-----
// Get all relevant events.  
    let events = await CalendarEvent.thisWeek([])
    const nextWeek = await CalendarEvent.nextWeek([])
    events.push(...nextWeek)
-----------
I changed it to the following method, why is it wrong?
---------------
// Get all relevant events.  
const dateLimit = new Date()
dateLimit.setDate(dateLimit.getDate()+ numberOfDays)    //
events = await CalendarEvent.between(this.now, dateLimit)   //Get events from now to dateLimit
--------------
For example, I want to display events in the next 20 days，I assign 20 to numberOfDays.
It should be able to display calendar events within 20 days. But it still shows calendar events for this week and next week.
Why does this problem occur? It's embarrassing. 😅
Hope to answer this question. Thank you

**Comment by mzeryck** [comment]
@Aellus I know it's been a while, sorry I took a break from this project. I've fixed my code so that there's no longer a limit on how many events you can show. (The old code was only pulling events from this week and next week - I expanded it so it can pull from any date now!)
