### ISSUE TITLE
Error: on line 1635:29

### ISSUE THREAD

**Issue by bckelley** [mzeryck/Weather-Cal#137]
This just happened I haven't done anything and before I delete is their a fix ![image](https://user-images.githubusercontent.com/15696431/115269948-70890800-a101-11eb-8ee8-2eb57635021d.png)

**Comment by bckelley** [comment]
Hello?

**Comment by mvan231** [comment]
A user in our discord server said resetting the widget helped them fix the issue

**Comment by mzeryck** [comment]
@bckelley I stepped away from this project for a while - please let me know if you're still having this issue!

**Comment by icsAT** [comment]
Looks like the same issue as #120.

I thik there is somehow a cache problem. We had a few people with problems like that out of the nowhere. You could track it down by removing one item by another to find wich item is causing the problem and wich cache file is not working and deleting it. You also could use the function "completely reset Widget", but then you have to redo all the settings.

Or Max could check if he could build an error handler when reading the cache and delete corrupt cache files and keep on working as there was no cache file.

**Comment by mzeryck** [comment]
I know my caching code is a bit brittle - if something fails, or the data doesn't make sense, I believe it will still write it to disk. So I agree that better error handling would be good here.

**Comment by epizzarello** [comment]
@mzeryck Can I be assigned this issue? It happened on mine and I already implemented a fix that worked.

**Comment by mzeryck** [comment]
@epizzarello Thank you for adding this!
