### ISSUE TITLE
iOS 15 support?

### ISSUE THREAD

**Issue by nolandperry** [mzeryck/Weather-Cal#138]
Everything stopped working when I updated to iOS 15 beta 1. I know it's only the first beta, but my question is if you plan on updating everything to work on iOS 15. Thanks!

**Comment by iameduardod** [comment]
@mzeryck any luck here?$

**Comment by mzeryck** [comment]
Closing this because it appears to work in iOS 15! (Wondering if there were issues with Scriptable with the betas.)
