### ISSUE TITLE
sunrise/sunset not working

### ISSUE THREAD

**Issue by Goldsucher** [mzeryck/Weather-Cal#14]
I think there is a problem with the sunrise/sunset feature. Checked it with default configuration (only api key added). The widget shows only the sunset-icon and "12:00 AM"

I tested the api request and it themes to work. 

Could you please check that?

**Comment by mzeryck** [comment]
Can you use [Pastebin](http://pastebin.com) and copy all of your code in there (without the API key, and removing any hard-coded location info if you've added it).

**Comment by Goldsucher** [comment]
sure. I've hardcoded the location but for pastebin I commented it out and paste your setupLocation-method.

https://pastebin.com/VzVL8Usi

**Comment by mzeryck** [comment]
Can you attach a screenshot of your widget? The code you sent works fine whether or not I use the built-in location function or the hard-coded one.

**Comment by Goldsucher** [comment]
okay strange, since tonight it is actually working. But it only shows sunrise. Shouldn't it show sunrise + sunset? 

here is the screenshot:
![widget](https://user-images.githubusercontent.com/7906131/96989061-72dd2180-1525-11eb-8cc1-012e9b54b2b7.jpg)

**Comment by mzeryck** [comment]
Ahh, so the current implementation tries to "guess" which time is more relevant - showing the sunrise in the morning, and the sunset in the evening. But I've been meaning to adjust the logic since it doesn't work that well. I'll update this issue when I have time to address it!

**Comment by mzeryck** [comment]
@Goldsucher I believe I've (finally) fixed this issue! In my testing, this finally works as designed (show today's sunrise / today's sunset / tomorrow's sunrise throughout the day).
