### ISSUE TITLE
Display issues with medium sized WeatherCal widget

### ISSUE THREAD

**Issue by CapitalistVN** [mzeryck/Weather-Cal#140]
![image](https://user-images.githubusercontent.com/87846733/126853081-f4531e67-708e-4e29-967a-75eb19b9dff7.png)
The medium-sized WeatherCal widget is not displaying properly. Other sizes work fine. What could be the problem?

**Comment by mzeryck** [comment]
@CapitalistVN Weather Cal isn't actually super smart - if there is too much stuff in the widget, it will get cut off. You could try going to Edit preferences > Text sizes, colors, and fonts and then changing the date format settings so it's not as big of a font size.
