### ISSUE TITLE
Cannot pick my work calendar

### ISSUE THREAD

**Issue by jacobodgaard** [mzeryck/Weather-Cal#142]
Hello! Thank you very a very nice script, I'm already loving how it looks on my phone!

I do have on issue though that I have not been able to find a solution to. I was wondering why I don't see all my calendar events, and noticed that I am unable to pick my work calendar, probably because it's from an exchange server, i.e. not on my iCloud. Is there any way to add it? 

Thank you in advance

**Comment by icsAT** [comment]
I have the same problem, but not found a solution so far. Did you?

**Comment by mzeryck** [comment]
@jacobodgaard @icsAT I know it has been a few months - if either of you are still having this issue, can you please create a new script and paste the following code:
`const calendars = await Calendar.forEvents()
for (item of calendars) {
  console.log(item.title)
}`
Then, see if the calendar you're looking for appears in that list? (If it doesn't, it means Scriptable isn't seeing it.)

**Comment by icsAT** [comment]
Hey @mzeryck,
glad to hear from you. Hope you are doing all right. I checked this again (I think I already did before). In my case the calendar I am looking for (my company exchange calendar) is not shown.

Greetings André

**Comment by mzeryck** [comment]
@icsAT Thank you for checking! Sadly, this means it's an issue with Scriptable itself, rather than with the Weather Cal script. I'll close this issue for now but I will be happy to fix if Scriptable is updated.
