### ISSUE TITLE
"News" problem: Certain RSS feed is displaying the Channel title instead of Article title

### ISSUE THREAD

**Issue by robinogi** [mzeryck/Weather-Cal#143]
I'm trying to use https://rss.cbc.ca/lineup/topstories.xml to pull News stories.

Instead of showing the title of the first article, WeatherCal 'News' is showing "CBC | Top Stories" which is the title of the RSS Channel/Feed.

Below is an excerpt of the beginning of the RSS file:

`<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:cbc="https://www.cbc.ca/rss/cbc" version="2.0">
  <channel>
    <title><![CDATA[CBC | Top Stories News ]]></title>
    <link>http://www.cbc.ca/news/?cmp=rss</link>
    <description>
      <![CDATA[
      FOR PERSONAL USE ONLY
      ]]>
    </description>
    <language>en-ca</language>
    <lastBuildDate>Fri, 27 Aug 2021 12:28:04 EDT</lastBuildDate>
    <copyright><![CDATA[Copyright: (C) Canadian Broadcasting Corporation, http://www.cbc.ca/aboutcbc/discover/termsofuse.html#Rss]]></copyright>
        <docs><![CDATA[http://www.cbc.ca/rss/]]></docs>
    <image>
      <title>CBC.ca</title>
      <url>https://www.cbc.ca/rss/image/cbc_144.gif</url>
      <link>https://www.cbc.ca/news/?cmp=rss</link>
    </image>
    <item cbc:type="contentpackage" cbc:deptid="2.630" cbc:syndicate="true">
      <title><![CDATA[Canada urges those left in Afghanistan to stay put and not lose hope]]></title>
            <link>https://www.cbc.ca/news/politics/afghanistan-canada-mission-1.6155450?cmp=rss</link>
      <guid isPermaLink="false">1.6130132</guid>
      <pubDate>Wed, 4 Aug 2021 20:38:17 EDT</pubDate>
                        <author></author>
      				      <category>News</category>
      <description>
        <![CDATA[
                        <img src='https://i.cbc.ca/1.6152338.1629875217!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_460/afghanistan.jpg' alt='Afghanistan' width='460' title='In this image provided by the U.S. Marine Corps, families board a U.S. Air Force Boeing C-17 Globemaster III during ongoing evacuations at Hamid Karzai International Airport, Kabul, Afghanistan, Tuesday, Aug. 24, 2021. (Sgt. Samuel Ruiz/U.S. Marine Corps via AP)' height='259' />                <p></p>
        ]]>
      </description>
    </item>
    <item cbc:type="story" cbc:deptid="2.632" cbc:syndicate="true">`

Using the example above, I assume the expected behaviour is that the 'News' section would display _"Canada urges those left in Afghanistan to stay put and not lose hope"_ instead.

**Comment by mzeryck** [comment]
@robinogi Thank you for submitting this, and sorry for how long it took to resolve - I took a break from this project. The newest version should fix this by being a bit smarter with its RSS parsing. (Also note that the link has changed to https://www.cbc.ca/cmlink/rss-topstories since this was submitted!)
