### ISSUE TITLE
Weather icons lack color

### ISSUE THREAD

**Issue by Nathaniell1** [mzeryck/Weather-Cal#144]
Hi,

I am on iOS 15 with iPhone 13 mini.
When I installed this script, I noticed that my weather icons (current at the right top corner, next hour a bit lower under it and sunrise/sundown) are all black in default options. I was unable to find anywhere how to change their color (only managed to change the text or turn all white with "Icons match text color -> always"). You have some preview icons on this github page where it shows clouds + sun in one image with two different colors - so I assume changing of icons color is not possible, because it would be a mess in the options.

I have also tried changing Symbols color, with absolutely no effect.

Is there anything else I can try to change to make the icon colors show or is this a bug?

**Comment by Gunner237** [comment]
Experiencing the same issues on iPhone 12 mini - all worked on iOS 14 and then all icons black on iOS 15

**Comment by mzeryck** [comment]
I believe this was a bug in the Scriptable app itself that was fixed!
