### ISSUE TITLE
Hourly forcast 

### ISSUE THREAD

**Issue by felho001** [mzeryck/Weather-Cal#148]
Hi can you tell me why not showing temperature hourly forcast. I don't know how to fix it. Thx
![66F6135E-B1A3-4A17-8030-B5B481E66D7B](https://user-images.githubusercontent.com/45117257/136146220-a48e05e1-a7cf-4d92-a802-dd1450685869.jpeg)

**Comment by icsAT** [comment]
Maybe the right column needs more space or a smaller font. You could set the column size in the code and the font in the settings.
