### ISSUE TITLE
Keine Anzeige Erinnerungen

### ISSUE THREAD

**Issue by Tobi197** [mzeryck/Weather-Cal#149]
Zeigt bei mir keine Erinnerungen an. Liste habe ich ausgewählt. 
![C0BA0B24-A7AC-4BBF-B208-68C4033B2F1E](https://user-images.githubusercontent.com/92183247/136618271-2999a941-bf1b-4d37-a42f-9f0dc3073fbc.png)

**Comment by icsAT** [comment]
Did you set reminders in the layout part of the code?

**Comment by mzeryck** [comment]
@Tobi197 Are you still experiencing this issue? Also, my apologies but I'm only able to communicate in English.

**Comment by Tobi197** [comment]
@mzeryck No problem anymore. It works.
