### ISSUE TITLE
JSON error after fresh installation

### ISSUE THREAD

**Issue by schlikkes** [mzeryck/Weather-Cal#150]
![image](https://user-images.githubusercontent.com/10193927/140938658-bb602285-cae6-492e-8241-9c730823f2df.png)

After the widget worked for quite a time, it stopped working by showing the error above. Also completely uninstalling and installing it again will no longer work.

**Comment by icsAT** [comment]
This is a cache problem. Widget Setup (run from app) => Other settings => Completely reset widget should fix it. But (!!!) it might clear other settings too and you have to re-set your configuration. You also could try to find out which item causes the error by deactivation one after the other and change the name of the cache file if you found the right one.

**Comment by schlikkes** [comment]
In deed this solved the issue. Cool that this reset has been already integrated into the widget.
