### ISSUE TITLE
Error on line 1635:29

### ISSUE THREAD

**Issue by civicdriver80** [mzeryck/Weather-Cal#152]
I don‘t make any changes. Since today it shows error on line 1629:29 Syntax error JSON parse error: unecpected EOF

**Comment by icsAT** [comment]
This might be a cache problem. Widget Setup (run from app) => Other settings => Completely reset widget should fix it. But (!!!) it might clear other settings too and you have to re-set your configuration. You also could try to find out which item causes the error by deactivation one after the other and change the name of the cache file if you found the right one.

**Comment by mzeryck** [comment]
@civicdriver80 I know it's been a few months - are you still experiencing this issue?

**Comment by civicdriver80** [comment]
I have deleted the Script.
