### ISSUE TITLE
country names in covid data

### ISSUE THREAD

**Issue by enochling** [mzeryck/Weather-Cal#157]
it seems that it doesn't work for countries with names more than one words (e.g. new zealand, hong kong etc)

tried to wrap it with different quotation marks but still not working.

**Comment by pandu1990** [comment]
Space is encoded with `%20` in the URLs
https://coronavirus-19-api.herokuapp.com/countries/New%20Zealand

**Comment by mzeryck** [comment]
I've fixed the parsing of the "Country for COVID information" setting to work better without needing to change the URL.
