### ISSUE TITLE
Images are slightly blurred

### ISSUE THREAD

**Issue by blakkkk** [mzeryck/Weather-Cal#158]
![image](https://user-images.githubusercontent.com/23288358/156492254-1711f2fb-11ba-40ed-8694-2d915ce0c44e.jpeg)

As you may see in the image above the Weather Cal background has a slight blur.

**Comment by mvan231** [comment]
Have you recently started using a different phone?

You might need to capture another screenshot of your background to get the image slices to match up with the new device

**Comment by blakkkk** [comment]
No; I have attempted screenshotting and cropping multiple times

**Comment by mvan231** [comment]
What do you mean cropping? The script should make the image slices for you with no need for manual cropping

**Comment by blakkkk** [comment]
Does Weather Cal automatically crop the background to size? I didn't think it did and have been using a shortcut named Transparent Icon Creator to crop a screenshotted image of my background (on the last page of the edit home screen) to the size of a medium widget.

**Comment by mzeryck** [comment]
This is an issue with the Scriptable app, not Weather Cal. I used the same source image in Scriptable and in Widgy to test this. Here is Scriptable - you can see the edge of the widget, where the lines get a bit blurry:
![scriptable](https://user-images.githubusercontent.com/71023727/159599149-e6153876-0601-4217-be05-1d52e66e137f.png)

And here is Widgy. I can't see the boundary.
![widgy](https://user-images.githubusercontent.com/71023727/159599199-76af8679-611c-43a9-8f54-1aab0862e519.png)

I believe I have mentioned this issue to Simon, the developer of Scriptable before. But without a fix from the app itself, sadly there is not much I can do.
