### ISSUE TITLE
Support for Darkmode Image?

### ISSUE THREAD

**Issue by igregma** [mzeryck/Weather-Cal#16]
Hi,

any plans to support a second image for the automatic switch to darkmode?
Just realize that widget looks shitty at night ;)

**Comment by mzeryck** [comment]
It's funny, I never noticed this issue because I have the setting "Dark Appearance Dims Wallpaper" turned off (it's in Settings app > Wallpaper). I'll consider adding this, although Scriptable's current support for dark mode unfortunately make it a bit difficult to implement.

**Comment by igregma** [comment]
Would be great if you can script a solution... :-)
At the moment I switched to another background which is cool also with one mode.... But I really love the ability to switch theme at nigth. If you take a look to 14.2 Beta, there's a ton of new cool bright/dark images included :-)

**Comment by igregma** [comment]
...just saw another Script is using this variable here:
(Device.isUsingDarkAppearance()
to set another Color. Maybe you can use it to set another image?
Cross fingers :-)

**Comment by mzeryck** [comment]
Unfortunately, isUsingDarkAppearance() is [no longer supported in widgets](https://docs.scriptable.app/device/#isusingdarkappearance). It never worked particularly well in testing, and the developer of Scriptable has said it isn't possible. Sorry about that!

**Comment by aschilling** [comment]
Hi,
I found the following workaround for enabling different backgrounds for light and darkmode in an automator forum:

```
  async function isUsingDarkAppearance() {
    const wv = new WebView()
    let js ="(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches)"
    let r = await wv.evaluateJavaScript(js)
    return r
  }
```
Using this function and modifying the loading process of the image in the the following way:
``` // Determine if our image exists.
    const dirPath = files.joinPath(files.documentsDirectory(), "Weather Cal")
    let darkTheme = await isUsingDarkAppearance();
    let prefix = (darkTheme)? "-dark": ""
    const path = files.joinPath(dirPath, name + prefix + ".jpg")
    const exists = files.fileExists(path)
```

So far, the code works well, however, only when manually triggering a widget preview via the Scriptable app beforehand. On its own it doesn't refresh the background. Do you have an idea what the reason for this could be? Is the image loading function not always called?

Best
Andy

**Comment by aschilling** [comment]
Sorry, I was wrong. My code works, the update intervall was just lagging behind the rest of the widget. Let me know if it works for you

**Comment by igregma** [comment]
Sounds Great! @mzeryck can you update your code with these new infos?
