### ISSUE TITLE
sunset/sunrise time doesn't show

### ISSUE THREAD

**Issue by jl10135** [mzeryck/Weather-Cal#161]
the widget displays -- in lieu of an actual time next to the sunset/sunrise icons. i've tried changing between having "sunset" and "sunrise" in the layout, using separate sunrise and sunset elements, and limiting the times displayed. 

![IMG_3635](https://user-images.githubusercontent.com/70981356/163700537-1fcfc4ff-d4f7-4f14-95c9-c26c7de3d6f8.jpg)

**Comment by icsAT** [comment]
The certificate of the api called is outdated. Hopefully the owner of the service will fix it soon.

**Comment by mzeryck** [comment]
It looks like this has been fixed by the API provider!
