### ISSUE TITLE
Issue connecting to sunrise-sunset

### ISSUE THREAD

**Issue by devenyi** [mzeryck/Weather-Cal#162]
I have been getting this message since yesterday. 

Error: The certificate for this server is invalid.
You might be connecting to a server that is
pretending to be "api.sunrise-sunset.org" which
could put your confidential information at risk.

**Comment by icsAT** [comment]
Same as #161.

The certificate of the api called is outdated. Hopefully the owner of the service will fix it soon.

**Comment by mzeryck** [comment]
It looks like this has been fixed by the API provider!
