### ISSUE TITLE
Feature request: Show / hide subtasks of reminders

### ISSUE THREAD

**Issue by YuriStruszczynski** [mzeryck/Weather-Cal#164]
Hi,

in reminders app you’re able to create subtask inside a reminder (by drag&drop). It would be cool to have the possibility to hide them.

best regards, Yuri

**Comment by mzeryck** [comment]
@YuriStruszczynski Unfortunately, this capability is not possible because Apple doesn't provide this information in the API. Hopefully they will add support for this in the future!
