### ISSUE TITLE
showing events as long as they last

### ISSUE THREAD

**Issue by hbfreak** [mzeryck/Weather-Cal#169]
Hey there,

is there a possibility to set „Minutes after event begins“ to the time the event ends?
I‘d like to show events as long as they last.

Thanks a lot
Daniel

**Comment by mzeryck** [comment]
This is a great idea! I'll add it to the feature requests that I will hopefully have time for soon.

**Comment by hbfreak** [comment]
This is working great now. Thank you so much! 😊
