### ISSUE TITLE
iOS 16.1 beta

### ISSUE THREAD

**Issue by EnricoBara** [mzeryck/Weather-Cal#180]
Widget stopped working since iOS 16.1 b1, I tried some change without any positive result. Is there a way to fix it? 
Still broken with beta 2 and beta 2

**Comment by mvan231** [comment]
> Widget stopped working since iOS 16.1 b1, I tried some change without any positive result. Is there a way to fix it?
> Still broken with beta 2 and beta 2

This is not a problem with the script / widget code. It's an issue ios 16.1 beta introduced. It's a known problem and still an issue in 16.1 dev beta 3. I personally have submitted feedback to Apple about it multiple times already. 

Simon tried fixing it with some workaround in the Scriptable Beta, but it didn't work still. 

FYI: Widgy is reportedly also not working with this beta.

**Comment by EnricoBara** [comment]
Thanks for the clarification, my bad thinking the code could be updated but some widgets are still working

**Comment by mvan231** [comment]
> some widgets are still working

Really? That is interesting! Even if I make a simple widget in Scriptable, it won't render.

Did you mean Scriptable widgets, or another app's widgets?

**Comment by EnricoBara** [comment]
Well, today I updated to ios 16.1 b3, no widgets are working, I also tried for some simple code with no good results. Maybe the previous widget was frozen and I didn't knew that ahah Hopefully Simon will fix it, I'm using the testflight version too.

**Comment by mvan231** [comment]
Simon tried to fix it but seems this is something Apple needs to fix as mentioned.

**Comment by mzeryck** [comment]
I'm not able to run betas on my phone, so thanks to everyone for the info. I'll leave this issue open until the issue between Scriptable and iOS is hopefully fixed.

**Comment by mintakka** [comment]
Same issue. I've also reported to apple via the feedback app. I suggest everyone else that finds themselves on this page do the same. squeaky wheels and all, you know

**Comment by EnricoBara** [comment]
The curious thing is that widgy and widgetsmith renders but no information is taken from calendars or reminders (ofc permissions are given) so it could be a scriptable+iOS combo because scriptable is unable to render neither an image or a plain text

![CCFBDCFC-03CB-48DB-A818-EC79DE2FD445](https://user-images.githubusercontent.com/12520941/193448541-dcd20594-1dd1-4ec8-9769-f1934707110a.png)

**Comment by EnricoBara** [comment]
The good thing is that with iOS 16.1 beta 4 widgets are back to work but the layout is kept to large even if I change the settings to medium (trying the default layout) 

![13A6E1D4-ABAF-4D67-B56B-53A5E1EF191B](https://user-images.githubusercontent.com/12520941/194014765-213f0a7d-cb2c-4b63-be3f-445f7f22f31e.jpeg)

**Comment by mintakka** [comment]
Just updated to 16.1 Public Beta 4 and medium Widgets are working again 

![image](https://user-images.githubusercontent.com/10188101/194324542-a382b87e-2c8e-4376-a876-9a7da300aaf4.jpeg)

**Comment by EnricoBara** [comment]
Yeah I forgot to close the issue sorry
