### ISSUE TITLE
I have two problems

### ISSUE THREAD

**Issue by farovitus** [mzeryck/Weather-Cal#19]
First, when i set _showLocation_ to true, i get null in the widget. I would really like to show my city name on this beautiful widget.

Second, the temperature is not similar to that in default weather app from iOS, and i am not talking here about 1-2'C but 5-7'C difference. Can't we somehow switch the service to another ? Something like [https://weather.com/weather/today/l/33.89011182351103,35.53696841112721](https://weather.com/weather/today/l/33.89011182351103,35.53696841112721) works perfectly fine and is more precise.

Also in openweathermap.org which option do you select from the following list of options [https://openweathermap.org/api#current](https://openweathermap.org/api#current)

**Comment by mzeryck** [comment]
Is location access enabled for the Scriptable app and widgets? You can check by going to the Settings app > Scriptable > Location.

Unfortunately, The Weather Channel charges money for their API access (according to number 5 in [this article](https://nordicapis.com/6-best-free-and-paid-weather-apis/)) so using their service currently isn't possible.

In OpenWeather, I'm using the [One Call API](https://openweathermap.org/api/one-call-api), which has the most options in the free version.

Does that help?

**Comment by deroverda** [comment]
Isn't the One Call API the only alternative you get when using their free plan? I signed up for a free account and got an API sent to me. Here's the details. [This](https://imgur.com/a/PvrBoGg) is the One Call API, right? And if not, how do I switch to One Call API?

**Comment by farovitus** [comment]
> Is location access enabled for the Scriptable app and widgets? You can check by going to the Settings app > Scriptable > Location.
> 
> 
> 
> Unfortunately, The Weather Channel charges money for their API access (according to number 5 in [this article](https://nordicapis.com/6-best-free-and-paid-weather-apis/)) so using their service currently isn't possible.
> 
> 
> 
> In OpenWeather, I'm using the [One Call API](https://openweathermap.org/api/one-call-api), which has the most options in the free version.
> 
> 
> 
> Does that help?

I have location turned on for scriptable and precise mode is on too, unfortunately location is null

**Comment by mzeryck** [comment]
@deroverda That looks right to me! If you haven't already, just go to the "API keys" tab, copy the key code, and paste it into the script, like this:
![IMG_9A7E3783A580-1](https://user-images.githubusercontent.com/71023727/97771508-c25db780-1afa-11eb-8d6a-bd4813c05e25.jpeg)

**Comment by mzeryck** [comment]
@farovitus Weird, I'm not sure why that would be happening. If you want, I'd be happy to try and troubleshoot further if you message me on Twitter or Reddit (I'm mzeryck everywhere).

**Comment by farovitus** [comment]
@mzeryck sorry for late reply, today i've updated the script with your latest changes.
I've got this error and i hope it helps, it actually shows up when i set lockLocation to false, but if i leave the latter to true it shows no error but i get null on the widget.
![image](https://user-images.githubusercontent.com/26744124/98131088-9c9e2d00-1ec3-11eb-812e-e43f752061ff.png)

**Comment by farovitus** [comment]
@mzeryck check this widget it have my city name working in the widget.
I left my cityWeather id so just go ahead and put your API to check it out... This widget IS NOT created by me.

_ // Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: yellow; icon-glyph: magic;
// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: deep-blue; icon-glyph: magic;
// Create your ID on openweathermap.org
// Get your api from there and set that in API_WEATHER
// To get CITY_WEATHER means city ID get the longitude and latitute from google maps for your location
// Replace the longitude, latitute and YOUR_API_KEY in the given link http://api.openweathermap.org/data/2.5/weather?lat=Latitude&lon=Longitude&appid=YOUR_API_KEY&units=metric and look for your city ID in the resultant text.
// Set that ID to CITY_WEATHER

//API_KEY
let API_WEATHER = "";//Load Your api here
let CITY_WEATHER = "276781";//add your city ID
let UNIT_TYPE = "C";//C for Celius and F for fernite

//create Data 
var today = new Date();

//Initlize Widget
let widget = new ListWidget(); 

//Get storage
var base_path = "/var/mobile/Library/Mobile Documents/iCloud~dk~simonbs~Scriptable/Documents/weather/";
var fm = FileManager.iCloud();

//color
var textcolor = new Color("#ffffff");

// Fetch Image from Url
async function fetchimageurl(url) {
	const request = new Request(url)
	var res = await request.loadImage();
	return res;
}

// Get formatted Date
function getformatteddate(){
  var months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  return months[today.getMonth()] + " " + today.getDate()
}

// Load image from local drive
async function fetchimagelocal(path){
  var finalPath = base_path + path + ".png";
  if(fm.fileExists(finalPath)==true){
    console.log("file exists: " + finalPath);
    return finalPath;
  }else{
    //throw new Error("Error file not found: " + path);
    if(fm.fileExists(base_path)==false){
      console.log("Directry not exist creating one.");
      fm.createDirectory(base_path);
    }
    console.log("Downloading file: " + finalPath);
    await downloadimg(path);
    if(fm.fileExists(finalPath)==true){
      console.log("file exists after download: " + finalPath);
      return finalPath;
    }else{
      throw new Error("Error file not found: " + path);
    }
  }
}

async function downloadimg(path){
    const url = "http://a.animedlweb.ga/weather/weathers25_2.json";
    const data = await fetchWeatherData(url);
    var dataimg = null;
    var name = null;
    if(path.includes("bg")){
      dataimg = data.background;
      name = path.replace("_bg","");
    }else{
      dataimg = data.icon;
      name = path.replace("_ico","");
    }
    var imgurl=null;
    switch (name){
      case "01d":
        imgurl = dataimg._01d;
      break;
      case "01n":
        imgurl = dataimg._01n;
      break;
      case "02d":
        imgurl = dataimg._02d;
      break;
      case "02n":
        imgurl = dataimg._02n;
      break;
      case "03d":
        imgurl = dataimg._03d;
      break;
      case "03n":
        imgurl = dataimg._03n;
      break;
      case "04d":
        imgurl = dataimg._04d;
      break;
      case "04n":
        imgurl = dataimg._04n;
      break;
      case "09d":
        imgurl = dataimg._09d;
      break;
      case "09n":
        imgurl = dataimg._09n;
      break;
      case "10d":
        imgurl = dataimg._10d;
      break;
      case "10n":
        imgurl = dataimg._10n;
      break;
      case "11d":
        imgurl = dataimg._11d;
      break;
      case "11n":
        imgurl = dataimg._11n;
      break;
      case "13d":
        imgurl = dataimg._13d;
      break;
      case "13n":
        imgurl = dataimg._13n;
      break;
      case "50d":
        imgurl = dataimg._50d;
      break;
      case "50n":
        imgurl = dataimg._50n;
      break;
    }
    const image = await fetchimageurl(imgurl);
    console.log("Downloaded Image");
    fm.writeImage(base_path+path+".png",image);
}

//get Json weather
async function fetchWeatherData(url) {
  const request = new Request(url);
  const res = await request.loadJSON();
  return res;
}

//start Programming

// Get Location 
/*Location.setAccuracyToBest();
let curLocation = await Location.current();
console.log(curLocation.latitude);
console.log(curLocation.longitude);*/
let unit_id = "";
let unit_s = "";
if(UNIT_TYPE=="F"){
  unit_id = "imperial";
  unit_s = "\u2109";
}else{
  unit_id = "metric";
  unit_s = "\u2103";
}
let wetherurl = "http://api.openweathermap.org/data/2.5/weather?id=" + CITY_WEATHER + "&APPID=" + API_WEATHER + "&units=" + unit_id;
//"http://api.openweathermap.org/data/2.5/weather?lat=" + curLocation.latitude + "&lon=" + curLocation.longitude + "&appid=" + API_WEATHER + "&units=metric";
//"http://api.openweathermap.org/data/2.5/weather?id=" + CITY_WEATHER + "&APPID=" + API_WEATHER + "&units=metric"

const weatherJSON = await fetchWeatherData(wetherurl);
const cityName = weatherJSON.name;
const weatherarry = weatherJSON.weather;
const iconData = weatherarry[0].icon;
const weathername = weatherarry[0].main;
const curTempObj = weatherJSON.main;
const curTemp = curTempObj.temp;
const highTemp = curTempObj.temp_max;
const lowTemp = curTempObj.temp_min;
const feel_like = curTempObj.feels_like;
//Completed loading weather data

// Widget Background Image
widget.backgroundImage = Image.fromFile(await fetchimagelocal(iconData+"_bg"));

//Start Spacing
widget.addSpacer(0);

//Widget weather Image
var img = Image.fromFile(await fetchimagelocal(iconData+"_ico"));
var widgetimg = widget.addImage(img);
widgetimg.imageSize = new Size(74,74);
widgetimg.rightAlignImage();

// Widget Date
var dateText = widget.addText(getformatteddate() + ", " + weathername);
dateText.textColor = textcolor;
dateText.font = Font.regularSystemFont(15);

// Widget Weather Temp
var tempText = widget.addText(Math.round(curTemp)+unit_s);
tempText.textColor = textcolor;
tempText.font = Font.boldSystemFont(35);

// Widget feel temp
let feel = "Feels like " + Math.round(feel_like) + unit_s;//"H:"+highTemp+"\u2103"+" L:"+lowTemp+"\u2103"
var hltempText = widget.addText(feel);
hltempText.textColor = textcolor;
hltempText.font = Font.regularSystemFont(15);

// Widget city Name
var citynameText = widget.addText(cityName);
citynameText.textColor = textcolor;
citynameText.font = Font.regularSystemFont(10);


// Bottom Spacer
widget.addSpacer();
//widget.setPadding(5, 15, 0, 15)

Script.setWidget(widget);_

**Comment by mzeryck** [comment]
@farovitus Thanks for writing back. This is an interesting issue. It actually isn't related to the weather API - the weather code you provided is using a different API endpoint.

Can you do me a favor: create a brand-new script, and paste the following code:
```
let files = FileManager.local()
let path = files.joinPath(files.documentsDirectory(), "weather-cal-loc")
console.log(files.readString(path))
```
If it works correctly, it should show your latitude, longitude, and city name in the console, like this: 37.332279|-122.010979|Cupertino. Let me know if it does that, or something else (of course no need to see the actual location, just curious if it works or not).

**Comment by farovitus** [comment]
@mzeryck thanks, yes it seems to work i get Lat|Long| null

**Comment by mzeryck** [comment]
@farovitus Thanks for checking! This is definitely a bug - I will let you know when I have time to fix it.

**Comment by mzeryck** [comment]
@farovitus I think the most recent version fixes this issue, please try it out and let me know!

**Comment by farovitus** [comment]
@mzeryck unfortunately it's not working either, tho it's a different issue now. Instead of having a "null" i am getting nothing now. Also i tried running your previous code, i get now _lat|long| _ only.

**Comment by mzeryck** [comment]
@farovitus Sorry, I made a mistake - can you change `const lockLocation = false` and run the script? This will reset the cache, and so if you change it back to `true` it should (hopefully!) work.

**Comment by farovitus** [comment]
@mzeryck sorry man, same behavior

**Comment by mzeryck** [comment]
@farovitus Okay that's weird since you said setting lockLocation = false worked for you earlier! Can you make a new script and run this code, and see what happens?
```
const location = await Location.current()
const geocode = await Location.reverseGeocode(location.latitude, location.longitude, Device.locale())
console.log(geocode[0].locality)
```

**Comment by farovitus** [comment]
> @mzeryck sorry for late reply, today i've updated the script with your latest changes.
> I've got this error and i hope it helps, it actually shows up when i set lockLocation to false, but if i leave the latter to true it shows no error but i get null on the widget.
> ![image](https://user-images.githubusercontent.com/26744124/98131088-9c9e2d00-1ec3-11eb-812e-e43f752061ff.png)

@mzeryck unfortunately it never did, i was having an error when setting it to false and when it was true it gave me a null but it never did show the name of my city. Also now with this code 

let files = FileManager.local()
let path = files.joinPath(files.documentsDirectory(), "weather-cal-loc")
console.log(files.readString(path))

It only shows lat|long|

**Comment by farovitus** [comment]
Okay maybe we are on the right track now since the code you gave me down below returned null

const location = await Location.current()
const geocode = await Location.reverseGeocode(location.latitude, location.longitude, Device.locale())
console.log(geocode[0].locality)

**Comment by mzeryck** [comment]
@farovitus That is so bizarre! Can you try changing the last line to be:
console.log(geocode)
When you do that, can you see your city name anywhere in there? For example, for me I can see it with both "city" and "locality".

**Comment by farovitus** [comment]
Okay here we go, below you can find the output, i replaced some of the values with xxxxx

2020-11-06 17:12:16: [{"locality":null,"areasOfInterest":null,"ocean":null,"subLocality":null,"postalCode":null,"isoCountryCode":"LB","country":"Lebanon","location":{"altitude":0,"latitude":33.xxxxxx,"longitude":35.xxxxxxx},"subAdministrativeArea":null,"name":"Rue xx","subThoroughfare":null,"administrativeArea":"Beirut","inlandWater":null,"timeZone":"Asia/Beirut","thoroughfare":"Rue xx","postalAddress":{"street":"Rue xx","isoCountryCode":"LB","city":"","state":"Beirut","postalCode":"","subLocality":"","subAdministrativeArea":"","country":"Lebanon"}}]

@mzeryck

**Comment by mzeryck** [comment]
@farovitus That is incredibly helpful, thank you!! I had no idea iOS might return null for both city and locality. I just posted a new version that, I think, fixes it. If you want you could also try updating the code, it's around line 690 where `locationData.locality` is defined, the new code is:
` locationData.locality = (geocode[0].locality || geocode[0].postalAddress.city) || geocode[0].administrativeArea`
Let me know if that works! I believe it should not correctly display "Beirut".

**Comment by farovitus** [comment]
Thanks @mzeryck you did it!! I hope it does not break for other people now that it worked for me.
![image](https://user-images.githubusercontent.com/26744124/98385388-9476f680-2057-11eb-94f5-c638019529f9.png)

**Comment by mzeryck** [comment]
@farovitus That is awesome news! And thank you so much for being incredibly patient while helping me figure this out. The way the code works, it shouldn't affect any existing users. Thanks again and have a great day!
