### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by matesalacz** [mzeryck/Weather-Cal#21]
Hey! 

I have the issue shown below. What can I do about it?
![image](https://user-images.githubusercontent.com/70015336/97725250-3df53f80-1ace-11eb-90a5-9f8e0798f897.png)

**Comment by mzeryck** [comment]
Have you claimed your OpenWeather API key, and added it to the top of the script? Near the top, it should look like this: `const apiKey = "abcdefjhijklmnop"`

**Comment by matesalacz** [comment]
> Have you claimed your OpenWeather API key, and added it to the top of the script? Near the top, it should look like this: `const apiKey = "abcdefjhijklmnop"`

Yes I did. Is this wrong?![image](https://user-images.githubusercontent.com/70015336/97750723-a73a7a00-1af1-11eb-8222-3fc1092e459d.png)

**Comment by mzeryck** [comment]
@matesalacz Ah, you only need the code after the second equals sign. For example, mine looks like this (key is partially hidden):
![IMG_9A7E3783A580-1](https://user-images.githubusercontent.com/71023727/97771508-c25db780-1afa-11eb-8d6a-bd4813c05e25.jpeg)

**Comment by matesalacz** [comment]
> @matesalacz Ah, you only need the code after the second equals sign. For example, mine looks like this (key is partially hidden):
> 
> ![IMG_9A7E3783A580-1](https://user-images.githubusercontent.com/71023727/97771508-c25db780-1afa-11eb-8d6a-bd4813c05e25.jpeg)
> 
> 
> 
> 

Ahh my bad. Now it works. Thanks for the reply 🙏🏻

**Comment by mzeryck** [comment]
No problem, glad it works!
