### ISSUE TITLE
I got an error message

### ISSUE THREAD

**Issue by TheRealEvan584** [mzeryck/Weather-Cal#22]
2020-10-31 13:57:08: Error on line 758:51: TypeError: undefined is not an object (evaluating 'weatherDataRaw.current.temp')

That is the error I received when trying to set up my widget for the first time. What does it mean and how can I fix it?

**Comment by igregma** [comment]
I know this error. Think you just created the weather acc? Sometimes you have to wait at least 24h before you acc starts working...

**Comment by TheRealEvan584** [comment]
It has been almost 30 hours now and I am still receiving the same error message. What can I do
to fix it?

**Comment by igregma** [comment]
Did you allow location access? What's your setting for location, fixed or constant location usuage?

**Comment by TheRealEvan584** [comment]
“While Using the App or Widgets” is my location setting for scriptable in iOS.

**Comment by TheRealEvan584** [comment]
I just solved my issue. I entered the weather API key incorrectly. Thank you for helping me in resolving this issue.
