### ISSUE TITLE
Making sure I'm using your latest script. How? 

### ISSUE THREAD

**Issue by deroverda** [mzeryck/Weather-Cal#24]
Thanks for this fantastic work. 
I've just gotten started with this and downloaded your latest .js a week ago. I've noticed since I started using your widget you've made more commits (bug fixes etc). What's the best way of keeping your script updated in my scriptable app without having to re-enter my personal edits to the .js file? Scriptable doesn't auto-update the script when you make commits right?

I assume the only way to keep it updated is that I re-download your latest .js file and then manually edit my personal details?
Maybe I shouldn't even try to fix something that isn't broken, hehe. There's just something in my brain that wants to make sure I'm using the latest version of everything. OCD I guess. 
Thanks again. 

*edit. just checked the latest .js script. did you change the color of the battery? my phone is 100 % and the battery icon is now black in color, when it used to be white.

**Comment by mzeryck** [comment]
@deroverda So sorry for the late reply. I've been thinking about this, and I've seen some solutions that may work. So it's definitely something I am going to look into!

For the battery color, there is a new setting: if you want, you can have the icons match the color of the text around them. This helps if you want black text on a white background, since the icons default to white. You can change this setting with `tintIcons` (setting to true or false). I hope that helps!

**Comment by deroverda** [comment]
@mzeryck No need to say sorry. It helped for sure. Before I close this I would like to ask one more question. 

For some odd reason my Greeting text looks like [this ](https://imgur.com/a/FOKvxlc)on my widget: 
Good
morning. 

The scriptable preview window shows it the [correct ](https://imgur.com/a/Gx9dxFo)way though:
Good morning. 

While I think it looks cool to be able to have the greeting split into two lines I would like to be able to view it the correct way. I've been messing around with "space," but no matter what I do the text is still split. If I remove/add "space," the text will either be too far down or too far up. I want the greeting in my current position. 

Here's the code:

`/*
 * SETUP
 * Use this section to set up the widget.
 * ======================================
 */
 
// To use weather, get a free API key at openweathermap.org/appid and paste it in between the quotation marks.
const apiKey = ""
 
// Set the locale code. Leave blank "" to match the device's locale. You can change the hard-coded text strings in the TEXT section below.
let locale = "en"
 
// Set to true for fixed location, false to update location as you move around
const lockLocation = true
 
// The size of the widget preview in the app.
const widgetPreview = "large"
 
// Set to true for an image background, false for no image.
const imageBackground = true
 
// Set to true to reset the widget's background image.
const forceImageUpdate = false
 
// Set the padding around each item. Default is 5.
const padding = 5
 
// Decide if icons should match the color of the text around them.
const tintIcons = false
 
/*
 * LAYOUT
 * Decide what items to show on the widget.
 * ========================================
 */
 
// You always need to start with "row," and "column," items, but you can now add as many as you want.
// Adding left, right, or center will align everything after that. The default alignment is left.
 
// You can add a flexible vertical space with "space," or a fixed-size space like this: "space(50)"
// Align items to the top or bottom of columns by adding "space," before or after all items in the column.
 
// There are many possible items, including: date, greeting, events, current, future, battery, sunrise, and text("Your text here")
// Make sure to always put a comma after each item.
 
const items = [
 
  row,
 
     column,
     date,
     battery,
     sunrise,
     space,
     greeting,
     space,
     space,
 
     column(90),
     current,
     future,
 
   row,
 
     column,
 
]`

**Comment by mzeryck** [comment]
@deroverda One thing to know, the preview inside Scriptable is sometimes inaccurate. The only way to know exactly how iOS will display your widget is to look at the home screen. I have [this shortcut](https://www.icloud.com/shortcuts/6682b3bc2ebe4b6c88bd024a78ad816a) saved to my homescreen, which forces all Scriptable widgets to refresh. That way I can test my widgets without relying on the in-app preview.

As for the greeting getting cut off, I've rearranged the layout code a bit. Basically, if you put the greeting inside its own row, it won't get cut off by the column on the right! Also, `space,` is a flexible space, so it will try and expand to the largest size possible. Adding multiple will make weird layouts. But, you can specify the size of the space like this: `space(50),` to use a fixed-size space. Try replacing your layout code with the following:

```
const items = [
  row,

     column,
     date,
     battery,
     sunrise,
     space(50),

     column(90),
     current,
     future,

   row,

     column,
     greeting,
     space,
]
```

**Comment by deroverda** [comment]
@mzeryck thanks for the thorough reply and for the shortcut. your code worked like a charm. thanks again. case closed 😃

**Comment by mzeryck** [comment]
Yay glad to hear that! Happy to help. And no worries I'll close from here. Cheers.
