### ISSUE TITLE
Make it whole Localization.

### ISSUE THREAD

**Issue by italoboy** [mzeryck/Weather-Cal#25]
I want to see battery, weather, next hour weather, weather condition and city to be locale.

Thank you.

**Comment by mzeryck** [comment]
Hello, have you tried setting the `locale` variable? It should affect all of the weather information. Does that work?

**Comment by italoboy** [comment]
> 
> 
> Hello, have you tried setting the `locale` variable? It should affect all of the weather information. Does that work?

Yes only the date and sunrise work.

**Comment by mzeryck** [comment]
Is location access enabled for Scriptable? You can check by going to the Settings app > Scriptable > Location > While Using the App or Widgets

**Comment by italoboy** [comment]
> Is location access enabled for Scriptable? You can check by going to the Settings app > Scriptable > Location > While Using the App or Widgets

Yes for weather once.
But my question was something else, my language is fa_IR and when I put it there I see weather and sunrise to be localized only.

**Comment by mzeryck** [comment]
Oh wow, thank you for bringing this up! There are actually two bugs here - OpenWeather leaves certain things in English, even if another language is selected. And, they don't support as many languages as the iPhone does.

But, I can fix both problems so they work better! I think I will have time to fix this after work today, but I will definitely let you know once I do. Sorry about that.

**Comment by mzeryck** [comment]
@italoboy Thanks again for bringing up these issues! I just released a new update to the code. Can you try and see if it works better?

**Comment by italoboy** [comment]
> @italoboy Thanks again for bringing up these issues! I just released a new update to the code. Can you try and see if it works better?

First thank you for supporting,second I've tried the updated script:

https://i.imgur.com/epJ6reU.jpg

As you can see, weather condition has been localized, but weather city name, next hour as well as calendar are not yet.

Calendar might be another another story and related to Apple calendar app (not sure if it is possible to be localized and show in my language based on locale code)

But the name of city and next hour weather could be localized.

Even battery percentage.

Thank you

**Comment by mzeryck** [comment]
Ah okay, can you please change `const lockLocation = true` and run the script once? This will force the location to update, and then the city should display in the correct language. 

If you'd like to change the language of the "Next hour" text and some other hard-coded text in the widget, you can scroll down to the `localizedText` section and change them manually. 

You are correct about the calendar - the script just displays the events as they appear on your calendar. 

For the battery percentage, how could it be localized? I'm just not familiar enough to know how it could be different, since it appears the same as the battery percentage in the status bar of the phone.

**Comment by italoboy** [comment]
I put const lockLocation = false and nothing happened. Tried several times and no.

Please tell me which line is localizedText for Tomorrow weather?! I couldn't find it.

OK battery is not a big deal here, I agree.

**Comment by SayWhat69** [comment]
Nvm it’s just black.

**Comment by mzeryck** [comment]
For the location issue, can you try creating a new script and pasting in this code:
```
const location = await Location.current()
const geocode = await Location.reverseGeocode(location.latitude, location.longitude, "fa_IR")
console.log(geocode[0].locality)
```
And let me know what it shows? That will help me figure out what might be happening.

For the localizedText, here is a screenshot showing where it is in the code. Any of the English text can be edited and changed to your own language!
![IMG_4AFC0BDCD01C-1](https://user-images.githubusercontent.com/71023727/98449893-9d65d780-20ec-11eb-990b-b9323aa517a7.jpeg)

**Comment by italoboy** [comment]
Hi,

I put the code under locklocation , it worked but only by turning on the location service each time and if I don't enable location service it wont't load and says "this can be changed from the system settings", if possible to read the location data once like weather api for the first time script running?!

![image](https://user-images.githubusercontent.com/61342502/98457022-af04b900-2198-11eb-8c72-cde33dffe7e8.png)

![image](https://user-images.githubusercontent.com/61342502/98457024-b4620380-2198-11eb-9095-b014ede550ab.png)

**Comment by firekollege** [comment]
is it possible to insert the battery level from an applewatch?
many thanks.

**Comment by mzeryck** [comment]
@italoboy Let me think more about this. I wrote the code assuming Scriptable would always have location access.

@firekollege Unfortunately, this is not currently possible in Scriptable.

**Comment by mzeryck** [comment]
@italoboy Hey, can you try downloading the newest version of the script? You will need to turn on location during setup, but after that, I believe it should work. Please let me know.

**Comment by italoboy** [comment]
> @italoboy Hey, can you try downloading the newest version of the script? You will need to turn on location during setup, but after that, I believe it should work. Please let me know.

Thank you mate, it is fine now and everything is perfect.😇👍🏻🥇

**Comment by mzeryck** [comment]
@italoboy Awesome!! Thanks for being so patient and glad it works!!
