### ISSUE TITLE
Exception Occured when running script

### ISSUE THREAD

**Issue by Nosh118** [mzeryck/Weather-Cal#26]
When running the script, I get the error 'Error on line 776.51: TypeError: undefined is not an object (evaluating 'weatherDataRaw.current.temp')

**Comment by mzeryck** [comment]
Have you added your [OpenWeather API Key](https://openweathermap.org/home/sign_up) to the script, and made sure location is enabled? (Settings app > Scriptable > Location > While Using the App or Widgets)

**Comment by Nosh118** [comment]
Sorted itself out now, thanks!
