### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Elboa99** [mzeryck/Weather-Cal#27]
In the info you said that if I wanted to have a transparent widget I had to run the transparent widget first and then at the end of that script export it to photos and use it in the weather script right? But I can't find any export to photos in the first script.

**Comment by mzeryck** [comment]
@Elboa99 What happens when you run that script? When you run it, the final popup should look like this:
![IMG_6894](https://user-images.githubusercontent.com/71023727/98256836-e4f53380-1f33-11eb-8f8f-1b01b7984efc.PNG)

**Comment by Elboa99** [comment]
No it's doesn't, I mean at least not on this script. That thing pop up in the other script, the Blurred widget ( correct me if I'm wrong 😅) I tried to run the transparent widget screen but that thing doesn't show up

**Comment by mzeryck** [comment]
If you're using Weather Cal, and you want to change the background image, you'll need to set `const forceImageUpdate = true` and run the script. Then it will allow you to choose a new background image. Does this help?

**Comment by Elboa99** [comment]
It does. Thanks a lot mate🔥

**Comment by mzeryck** [comment]
Glad to hear!

**Comment by mzeryck** [comment]
> Yo max can I ask you something? When you are less busy can you guide me trough step by step in changing the background of the widget into transparent? I don’t know anything about code and I tried several times to turn a widget background into a transparent one.
> 
> I read the disclaimer but still I dunno what to do

@Elboa99 Hey, moving this back over to Weather Cal. The easiest way to get transparent backgrounds is to use this script: (click this link on your phone): https://scriptable.app/gallery/transparent-widgets

**Comment by Elboa99** [comment]
Alright thanks a lot
