### ISSUE TITLE
How can I change the color of the tomorrow label in the calendar events

### ISSUE THREAD

**Issue by ArnavMotwani** [mzeryck/Weather-Cal#3]
I went through the code a couple times and couldn't find which item in the textFormat array changes the tomorrow label. Since the the tomorrow label is posing as an event, does it have to be the same color as the events? Note I am not talking about the future weather label.

**Comment by mzeryck** [comment]
Ah yep, you're right - currently it has to match the format of the event title. I can work on adding a condition to the `events` function that handles the label better.

**Comment by ArnavMotwani** [comment]
Yes I think the labels need to be a bit more distinct!

**Comment by mzeryck** [comment]
The most recent commit adds the `eventLabel` option in `textFormat` to target the tomorrow label.
