### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by suxus-zz** [mzeryck/Weather-Cal#30]
Hello
The widget is really awesome, if you have something else I would be missing the following.

1. The probability of rain in the next hour. I think the rain percentage can be found here (https://api.openweathermap.org/data/2.5/onecall?)

2. If you show both the events and reminders, it may be that an event is shown first, e.g. at 10:00. If there is a reminder at 9:00 am, it looks a bit confusing in the display

Event1
10:00
Reminder1
09:00

Perhaps a separation of events and reminders in the display would not be necessary but simply a chronological display.

09:00 Reminder1
10:00 Event1
11:00 Reminder2
11:15 Reminder3
11:30 event2

If you then maybe put time and title on one line, you could still save space.

These are just a few ideas / thoughts that might still be useful.

Thank you for the great job you are doing here.

**Comment by mzeryck** [comment]
Hi, thank you for these suggestions! I had already been planning to work on a combined events/reminders element, and the idea of putting the time/date on the same line is a good one. I can also look into rain percentage as well. I have a few other things to work on this weekend, but I will leave this issue open until I have time to work on it! Thanks!

**Comment by suxus-zz** [comment]
Hello, I have adapted / expanded your code a little for my needs.

- if you don't choose a background image and you don't want the gradient, you can define a background color
- The week number is also given in the date
- Battery color on green
- the current Covid information
- Texts in german
- Rain Precipitation in percent (in the future 1h or tomorrow)

I have not yet started the combination of events and reminders, but as already written you could certainly optimize some space if you only have one line per entry.

What is not quite clear to me, however, is why there is so much empty space between the two columns above (left and right) to the lower part (events, reminder).

If you are interested in my code changes, I can send it to you.

Many greetings

![IMG_1217](https://user-images.githubusercontent.com/17749132/98462605-c900c480-21b5-11eb-9c0f-7fdda4cccedf.jpeg)

**Comment by igregma** [comment]
Is it cool if I capture this isssue to add my own idea :-)

I would like an option to only show tomorrows event if it's later the day, like the option for tomorrow weather!

suxus-zz, I would like to get these covid code :-)

**Comment by suxus-zz** [comment]
Hello, I can make my adjustments/extensions available, but since the widget comes from @mzeryck , I definitely want him to give it okay. I actually just wanted to customize the widget for my needs.

Yesterday I also expanded the widget for myself so that events and reminders are no longer displayed separately and so they are then displayed chronologically, regardless of whether an event or a reminder, for me it is crucial that I know that I have to do something. It works, but I think that could certainly be optimized (especially graphically)

I also changed something on the background so that you can now choose between background image, background color, dynamic background gradient and fixed background gradient.

Many greeting

**Comment by mzeryck** [comment]
@suxus-zz Thanks for your contributions! You would definitely be welcome to submit a pull request with your new code. As for why there is so much space, it has to do with the LAYOUT section - the `space,` element is a flexible space, which pushes content to the edges of the widget.

@igregma I like your idea about tomorrow's events! I would recommend opening a new issue with this suggestion.

**Comment by igregma** [comment]
...will do :-)

**Comment by suxus-zz** [comment]
Hello
I do a new branch and make a pull request (it's my first i hope it's works).

regards

Thats a screen from my current version
![IMG_1223](https://user-images.githubusercontent.com/17749132/98561111-c632cc00-22a8-11eb-905f-499439c0a186.jpeg)

**Comment by noemi360** [comment]
Can any one of you guys send me the code you used for your widget so I can make mine from it and use it as a guide thx

**Comment by noemi360** [comment]
> Hello
> 
> I do a new branch and make a pull request (it's my first i hope it's works).
> 
> 
> 
> regards
> 
> 
> 
> Thats a screen from my current version
> 
> ![IMG_1223](https://user-images.githubusercontent.com/17749132/98561111-c632cc00-22a8-11eb-905f-499439c0a186.jpeg)
> 
> 

Can  send me the code you used for your widget so I can make mine from it and use it as a guide thx

**Comment by suxus-zz** [comment]
@igregma 
Hello, I expanded my code so that you can choose whether the events and reminders from today or the next 24 hours should be displayed.
My days are visually separated by a fine red line.
Many greetings

![IMG_1230](https://user-images.githubusercontent.com/17749132/98775036-9391ec00-23ec-11eb-83e4-5886c33d7a57.jpeg)

**Comment by igregma** [comment]
Looks great suxus-zz!
Looking forward to see your improvement merged here :-)

**Comment by mzeryck** [comment]
@suxus-zz Hmm, I'm not able to see any pull requests here (or forks on your profile). I'd definitely still be open to it, if you'd like!

**Comment by suxus-zz** [comment]
Hmm i make a pull request but i think i make something wrong (it was my frist time). Have you a email that i can send you my current version?

**Comment by sleepyhellow** [comment]
Is it possible to see the events and reminders for the next 10 days and the text starts on the top and at the Button?

**Comment by mzeryck** [comment]
@suxus-zz Hmm, it looks like the branch is even with my branch. If it's easier, you can upload your code here: http://gist.github.com and send me the link! I would be happy to look at integrating some of these features, and working with you on a pull request and crediting you.

**Comment by suxus-zz** [comment]
@mzeryck i send you a invite to my repo i hope it's works so.

**Comment by mzeryck** [comment]
@suxus-zz Thanks for the invitation! I'll take a look at it soon, I may not have time before this weekend.

**Comment by mzeryck** [comment]
@suxus-zz Hi, thanks again for your adjustments! I would definitely like to merge in the rain percentage and COVID information. It looks like your code is using a slightly older version of the script - would you like to submit a pull request with an update, or would you be OK with me adapting your code and giving you credit? Let me know, thank you!

**Comment by suxus-zz** [comment]
Hello, no problem you can adapting my code and so we have all the same code for the future.
Thank you very much

**Comment by mzeryck** [comment]
@suxus-zz Thank you again for your code! I've added the COVID and rain percentage features to Weather Cal, with a few tweaks. I am going to close this issue, but don't worry, I will also update the events/reminders.
