### ISSUE TITLE
Changing the Time

### ISSUE THREAD

**Issue by shamxna** [mzeryck/Weather-Cal#31]
Hello! Is there anyway to correctly put the time or keep the time up to date with my current one? Mine is stuck at 4:54 PM

**Comment by mzeryck** [comment]
Currently, there is no way to display the time on a Scriptable widget. It may be possible in the future if the developer adds this functionality.

**Comment by shamxna** [comment]
Gotcha, thank you for your work and for responding! I’m looking forward to more features you’ll be adding 👍!
