### ISSUE TITLE
Add Reminders When Listing Possible Elements in the Layout Section

### ISSUE THREAD

**Issue by TheRealEvan584** [mzeryck/Weather-Cal#33]
In the layout section of the code when listing possible items you forgot to mention reminders. This is the smallest of small changes but I guess it should be said. Thanks in advance.

**Comment by themicmaine** [comment]
The new version of your widget doesn't automatically refresh

**Comment by TheRealEvan584** [comment]
@themicmaine I know I can just copy the updated code.

**Comment by mzeryck** [comment]
@TheRealEvan584 This should be fixed in the newest version :)
