### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by Dimakap** [mzeryck/Weather-Cal#34]
Hi.

I have an issue with the Reminders on this widget. It only shows me the Verträge Reminder and not the other i have. 

I didn't changed anything Reminder based in the script. 

Thanks
![image](https://user-images.githubusercontent.com/73642725/98854958-8f50e780-245b-11eb-9dbe-2d0cf7f8542e.jpeg)

**Comment by mzeryck** [comment]
Can you try creating a new script, and pasting in this code:
```
const reminders = await Reminder.allIncomplete()
for (item of reminders) {
  console.log(item.title + " (" + item.calendar.title + ")")
}
```
Does this show all of your reminders as expected?

**Comment by Dimakap** [comment]
Yes. This works

**Comment by mzeryck** [comment]
Hmm, can you try looking at the reminders settings in the script? Specifically, the numberOfReminders, showWithoutDueDate, and showOverdue settings would affect the display of reminders.
![Screen Shot 2020-11-12 at 12 07 05 PM](https://user-images.githubusercontent.com/71023727/98990716-adf8c200-24df-11eb-841f-f5e78c3ab340.png)

**Comment by Dimakap** [comment]
I played around with the reminders settings on the script but it doesn't list my standard icloud reminders. 

Maybe i need to add some of my icloud information to the script?

**Comment by mzeryck** [comment]
That is odd. They don't show up even if you set `numberOfReminders = 0` and use a large widget?

**Comment by mzeryck** [comment]
I'm going to close this issue since I haven't heard back in a week - but please reopen it if you're still having issues on the latest version.
