### ISSUE TITLE
AM/PM to 24 hour clock

### ISSUE THREAD

**Issue by deroverda** [mzeryck/Weather-Cal#35]
Hi again, 

Title is pretty self-explanatory. for example right now the widget shows me that the sun will go down at` 3:51 PM` but I prefer to view the time as `15:51`. 
After midnight would be `03:51` instead of `3:51 AM`. 
Is this setting possible to change? 

Thanks in advance.

**Comment by suxus-zz** [comment]
Hello
If you set to

let locale = "de"

then you have 24 hour clock

regards

**Comment by deroverda** [comment]
@suxus-zz thanks for the reply. and yes, this makes the clock show it in the way I want but it also switches the widget language to german. I want everything in the original language (en) but I just want the clock displayed like I wrote above.

**Comment by mzeryck** [comment]
@deroverda It looks like Scriptable does not obey the iOS "24 hour time" setting. However, if you change your locale to "en_GB" it will work and remain in English.

**Comment by deroverda** [comment]
@mzeryck brilliant! it works. thank you so much.
