### ISSUE TITLE
Time-based events and reminder display

### ISSUE THREAD

**Issue by mzeryck** [mzeryck/Weather-Cal#36]
Is it possible to see the events and reminders for the next 10 days and the text starts on the top and at the Button?

_Originally posted by @sleepyhellow in https://github.com/mzeryck/Weather-Cal/issues/30#issuecomment-726309496_

**Comment by mzeryck** [comment]
@sleepyhellow Can you explain your request about the text on the top and bottom a bit more?

**Comment by sleepyhellow** [comment]
The text (events/reminders) are at the button of the widget. I would like to see it on the top (under weather text)

**Comment by jianyu-li** [comment]
@mzeryck is there a way to just show reminders that are due today?

**Comment by jianyu-li** [comment]
> @mzeryck is there a way to just show reminders that are due today?

Well today and overdue

**Comment by yuyuye84** [comment]
> @mzeryck is there a way to just show reminders that are due today?

Edit Weather Cal code.js. Around line 800. the function shouldShowReminder()
among several ifs, add another if like below:
`if ((new Date().setHours(23,59,59,999) - reminder.dueDate) < 0) { return false }`

FYI. It's quite a rough solution, and would be lost if you "update code".

**Comment by mzeryck** [comment]
I can look into adding a setting here! I personally don't use Reminders, so the existing code is based on someone else's work. Scriptable does provide a few built-in options for grabbing the reminders, so I can look into this.

**Comment by jianyu-li** [comment]
> I can look into adding a setting here! I personally don't use Reminders, so the existing code is based on someone else's work. Scriptable does provide a few built-in options for grabbing the reminders, so I can look into this.

Great! Thank you!

**Comment by marvelousmo1** [comment]
Mzeryck, That`ll be so nice if you could implement what jianyu-li suggested, so I can see only the overdue and the today reminders. Would it be possible to implement as well when a reminder is tapped that the reminder app will actually open?

Thank you soo much for this great script!

**Comment by mzeryck** [comment]
@jianyu-li This setting is now available! You can set `todayOnly` to `true`. The settings for overdue tasks and tasks without due dates are still separate settings - so you can pick any combination. Hope this helps!

@marvelousmo1 Regarding tapping each item, I tried and was not able to get it to work. Reminders do have a URL scheme, but for some reason Scriptable doesn't seem to allow it to work.

**Comment by jianyu-li** [comment]
> @jianyu-li This setting is now available! You can set `todayOnly` to `true`. The settings for overdue tasks and tasks without due dates are still separate settings - so you can pick any combination. Hope this helps!
> 
It’s...beautiful. Thanks @mzeryck !

**Comment by marvelousmo1** [comment]
Cool Max, Thank you soo much!!
Moritz
