### ISSUE TITLE
WeatherCal v2 message

### ISSUE THREAD

**Issue by farovitus** [mzeryck/Weather-Cal#37]
Hey @mzeryck thanks for the new update tho i have a little feedback about how the message is showing now, below is an example of how v2 shows it
![image](https://user-images.githubusercontent.com/26744124/98994254-3014d500-2538-11eb-85cc-ab298740d8ba.jpeg)

On v1 it used to show it like this
Enjoy the rest of your day, [name].

Anyway to revert this minimal change ?

**Comment by noemi360** [comment]
> Hey @mzeryck thanks for the new update tho i have a little feedback about how the message is showing now, below is an example of how v2 shows it
> ![image](https://user-images.githubusercontent.com/26744124/98994254-3014d500-2538-11eb-85cc-ab298740d8ba.jpeg)
> 
> On v1 it used to show it like this
> Enjoy the rest of your day, [name].
> 
> Anyway to revert this minimal change ?

How did you make it transparent

**Comment by TheRealEvan584** [comment]
@farovitus I agree this should be changed.

@mzeryck This same thing happens with the greeting. In v1 the whole greeting + my name fit on 1 line, but in v2 only the greeting is on the first line, my name is on the second. I would like it to fit on one line because it is more compact.

@noemi360 To make the background transparent you need to use another script to capture a part of your wallpaper which is then used as the background for the widget.

**Comment by mzeryck** [comment]
@farovitus @TheRealEvan584 I changed the default layout in v2. A lot of people never change the default layout, and this one works better in both medium and large widget sizes. But it's really easy to change to the old version. Just change the layout to this:

```
row 
  column
    date
    sunset
    battery 
    space
    
  column(90)
    current
    future

row
  column
    events
```

With events on their own row, they can take up the full width of the widget.

**Comment by TheRealEvan584** [comment]
@mzeryck Thanks for the tip!

**Comment by farovitus** [comment]
@mzeryck ah, it feels already much better now with this change. What's the reason behind your change if you don't mind me asking

**Comment by mzeryck** [comment]
@farovitus The old default looks horrible in a medium widget, so I changed the default. But I always intended for people to make their own layout customizations! :)
