### ISSUE TITLE
weather forecast

### ISSUE THREAD

**Issue by tie82** [mzeryck/Weather-Cal#38]
Just added the option to display forecast for the next 2 days including today:
If you like it, feel free to add it to the main repo

![file](https://user-images.githubusercontent.com/38699731/98996141-a9112e00-2532-11eb-8bd4-da2403f77a58.jpeg)

https://github.com/tie82/Weather-Cal

**Comment by mzeryck** [comment]
This is cool! I will admit, I am not sure how to merge this in without a pull request, please feel free to submit one!

**Comment by mzeryck** [comment]
This has now been merged into the main branch.
