### ISSUE TITLE
[Request] Change Event from Start Date to End Date

### ISSUE THREAD

**Issue by jianyu-li** [mzeryck/Weather-Cal#39]
Hi @mzeryck 

Would it be possible to change line 748 in the Weather Cal code.js file to 

`return (event.EndDate.getTime() > currentDate.getTime())` ? Or at least make it an option?

This would mean the event would still show even if it has already started (sometimes I'm late!). Then it goes away once the event is over. 

Thanks for your consideration!

**Comment by mzeryck** [comment]
Ah, I think this is a good idea! I think I will work on adding the ability to adjust this amount - for example, waiting 5 min versus 15 min.

**Comment by jianyu-li** [comment]
Cool!

**Comment by HelloSmithers** [comment]
Could reminders also be shown in the reverse order of what is in the picture attached?
![unnamed](https://user-images.githubusercontent.com/74478544/99162133-3d0b1180-274e-11eb-8fca-4c8a9755b823.png)

**Comment by mzeryck** [comment]
@jianyu-li The newest version of the code has this feature! If you want to update without changing your other widget settings, you can run the "Update code" function, and then add this setting to the EVENTS section: 
```javascript
// Minutes after an event begins that it should still be shown. 
,minutesAfter: 5
```
Please let me know if that works OK!

**Comment by jianyu-li** [comment]
You are on a roll tonight! Thanks!

**Comment by mzeryck** [comment]
This is what weekend procrastination looks like 😅 and no problem!

**Comment by jianyu-li** [comment]
Also thanks for telling me what line to add so I didn’t have to update my whole thing! Very helpful when you have it fine tuned just right :)
