### ISSUE TITLE
iPhone 12 Mini

### ISSUE THREAD

**Issue by arealhen** [mzeryck/Weather-Cal#40]
Hi, could you please update the script to support iPhone 12 mini? I can’t get my background to match up with the widget. Thank you! 
![968FC49D-6EF1-415E-90D3-BF9D6FCDF926](https://user-images.githubusercontent.com/74436281/99131268-9c600900-260a-11eb-8a0d-e30dad3f9365.jpeg)

**Comment by vesparider** [comment]
Same goes for the new iPhone 12 Pro Max - its support would be great.

**Comment by mintakka** [comment]
I noticed this issue to. The problem isn't actually in this script but rather in the script used to generate the "transparent" background image. 

I managed a temporary fix you can implement yourself. See my issue log and comment over in the correct script

https://github.com/mzeryck/Widget-Blur/issues/2

**Comment by mzeryck** [comment]
@arealhen Thanks for bringing this up, and thank you @mintakka for the adjustments! I would be happy to implement this fully & confirm the new measurements. Would either of you be willing to take a screenshot of a home screen full of small widgets? You don't need a fully white background, but it is helpful to have contrast between the widgets and the background image:
![8F30440C-9CB1-47D3-AA9A-A70B117C53A8](https://user-images.githubusercontent.com/8514778/97064511-27de0100-155b-11eb-921a-c945acf89ce8.png)

That way, I can measure the pixel positions precisely.

**Comment by arealhen** [comment]
Sure, no problem - hope this is okay: 
![Uploading 88C10277-8240-47CE-A6B2-4563CBA193BB.png…]()

**Comment by mzeryck** [comment]
@arealhen Thank you so much! The newest version should now work correctly on the mini. Let me know if you have any other issues!
