### ISSUE TITLE
Can't find variable: SFSymbol

### ISSUE THREAD

**Issue by dennisostlaender** [mzeryck/Weather-Cal#41]
Hi, I went through all the steps of setting up the widget and when I try to preview it it gives me an error.
"Exception Ocurred
Error on line 1527:50: ReferenceError: Can't find variable: SFSymbol"

**Comment by mzeryck** [comment]
Hi Dennis, can you confirm which version of Scriptable you're using? From the main page of the app, tap the gear in the top left, then About, to see the version number.

**Comment by dennisostlaender** [comment]
> Hi Dennis, can you confirm which version of Scriptable you're using? From the main page of the app, tap the gear in the top left, then About, to see the version number.

Holy smokes! I was way behind on the updates. I guess I wasn't used to not having automatic updates on TestFlight. I was on version 1.5.1 but am now on 1.6. It works flawlessly now, that is embarrassing ha. Thank you so much for the reply though!
