### ISSUE TITLE
Reminder sorting

### ISSUE THREAD

**Issue by mzeryck** [mzeryck/Weather-Cal#44]
Could reminders also be shown in the reverse order of what is in the picture attached (on the right hand side)?
![unnamed](https://user-images.githubusercontent.com/74478544/99162133-3d0b1180-274e-11eb-8fca-4c8a9755b823.png)

_Originally posted by @HelloSmithers in https://github.com/mzeryck/Weather-Cal/issues/39#issuecomment-727357364_

**Comment by mzeryck** [comment]
@HelloSmithers Can you tell me more about how you'd like the reminders to be sorted?

**Comment by HelloSmithers** [comment]
Notice how the reminders go 15 Nov, 16, Nov 15 Nov? I'd prefer they go 15 Nov, 15 Nov, 16 Nov.

Reminders don't have to have a time attached so not sure how easy this is

**Comment by blahsd** [comment]
For me currently they appear sorted by when creation date. I also would love them sorted by due date!

**Comment by mzeryck** [comment]
@HelloSmithers @blahsd I am happy to report that they now sort in order! You can just run the "Update code" option from the widget settings menu.

**Comment by blahsd** [comment]
Dude yessss you’re the man

________________________________

**Comment by lcar8ter** [comment]
Sorting is great how do you see the COVID section in the widget?
