### ISSUE TITLE
Sunrise and Sunset elements do the same thing

### ISSUE THREAD

**Issue by jianyu-li** [mzeryck/Weather-Cal#45]
So I know that it changes based on the time of day. But it seems like it doesn’t matter if I put sunrise or sunset in the layout it does the same thing. I wonder if maybe we should have a third option that does the same behavior as it does today (dynamically change) and have sunrise and sunset only show those respective elements. Thoughts?

**Comment by jianyu-li** [comment]
Here’s what I mean 
![539F1332-4E4E-4324-A6F7-5E0F3AA8E02A](https://user-images.githubusercontent.com/52750081/99212567-35fcf700-2780-11eb-84ab-57c1a9b73446.jpeg)
![Uploading DA5AA997-34A4-4C97-BCBF-4D0EDC2376BC.jpeg…]()

**Comment by mzeryck** [comment]
I've added this feature in the most recent version. If you use the Update code function, and then add this to your widget settings:
```
// Set to true to use separate "sunrise" and "sunset" elements. Default is false.
,separateElements: true
```
