### ISSUE TITLE
Show events that already started 

### ISSUE THREAD

**Issue by Stahl80** [mzeryck/Weather-Cal#46]
Hi. 

Thanks for your excellent script!!!

Is there a way to display events that started and have them disappear when they end?

**Comment by jianyu-li** [comment]
In the events section on the newest version there’s a spot to specify how many minutes after an event has started to show it. Looks like this 

`// Minutes after an event begins that it should still be shown. 
,minutesAfter: 30 `

**Comment by Stahl80** [comment]
I updated the script but I can’t see that section. Can I manually add it in?

**Comment by jianyu-li** [comment]
Yeah just copy that but of code into the events section

**Comment by jianyu-li** [comment]
The update button just updates the main code but not the script you add all your settings

**Comment by Stahl80** [comment]
Thanks!
I tried it, couldn’t get it to keep showing the event and the upcoming event next day stopped showing. 

Made a new with the updated code but that behaves the same way and next day event are not there.

**Comment by Stahl80** [comment]
Thanks! Managed to solve it :). 
Great work you made with this, looks good and a lot of customization available!

One thing I thought about, is it possible to make the battery symbol green (not the percentage) it turns red when low battery but for me it would look good with green when it’s over 20%, now it’s white.

**Comment by mzeryck** [comment]
Thanks @jianyu-li for helping out! @Stahl80 It would be possible to make it green, but since I am trying to match the status bar style, I'm not planning to add that feature.
