### ISSUE TITLE
Dynamic date broken

### ISSUE THREAD

**Issue by igregma** [mzeryck/Weather-Cal#47]
I just downloaded the latest version, looks like the display of large date is broken?
I double checked that dynamic date is set to true... the "no events message" is also displayed on the widget.
Of course low priority ;-)

**Comment by mzeryck** [comment]
Hmm, that's weird! It's still working for me. Did you use the "Update code" feature?

**Comment by igregma** [comment]
Yes... several times.
Possible that it's because I have some calendars with events, I just didn't choose for display?

**Comment by mzeryck** [comment]
Ah, this is a bug! If you update the code again, it should now work correctly.

**Comment by igregma** [comment]
...confirm :-)
Thanks!!
