### ISSUE TITLE
How to set the desired Calendar to be shown?

### ISSUE THREAD

**Issue by xisintag** [mzeryck/Weather-Cal#48]
I was wondering what to put in between the brackets to display only specific calendars?

```
// Set which calendars for which to show events. Empty [] means all calendars.
,selectCalendars: []
```

**Comment by jianyu-li** [comment]
@xisintag heres an example 

`_,selectCalendars: ["Work", "Family", "Holidays in United States", "TV Time Calendar", "Contacts"]_ `

**Comment by adamengineering** [comment]
Thx, that works!
