### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by adamengineering** [mzeryck/Weather-Cal#49]
Todays update broke the Reminders filter on my device. No matter what NUMBER I have in 

`// How many reminders to show. Use 0 for all.
    numberOfReminders: 0`

it displays all Reminders with a due date, prior to this release it only showed the NUMBER I wanted

**Comment by mzeryck** [comment]
Sorry about that! Please run the update again, this bug should now be fixed.

**Comment by lcar8ter** [comment]
I am receiving and unexpected end of script line 1985... anyone else get this?

**Comment by adamengineering** [comment]
Thx! Much appreciated ;-)

**Comment by mzeryck** [comment]
@lcar8ter You just need to add "reminders" to the layout section of the script! Depending on what layout you're using, you might need to rearrange things. Let me know if you need help.

@adamengineering There are two ways you can do this. Submitting a pull request allows you to provide your changes directly into the project, and it automatically credits you when I approve the change. Some people who are less comfortable with GitHub, or who prefer not to do the work of integrating it into the project, have just provided their code (by copying and pasting here, or using a [gist](http://gist.github.com)) for me to add and credit manually. It's up to you!

**Comment by adamengineering** [comment]
Let me try to submit a pull request ;-)
