### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rishi-desai** [mzeryck/Weather-Cal#5]
I'm getting this error when I run the code on Scriptable:

2020-10-08 21:56:38: Error on line 213:33: TypeError: undefined is not an object (evaluating 'data.current.temp')

**Comment by rajaspidey** [comment]
Am getting same error.

**Comment by rajaspidey** [comment]
> Error

It’s because api key is not active yet. I got the error 5 min ago and now it’s working.

**Comment by mzeryck** [comment]
Yes @rishi-desai - I'm not sure why, but it can take some time for OpenWeather to activate the key.
