### ISSUE TITLE
The weather isn’t updating 

### ISSUE THREAD

**Issue by ivyte** [mzeryck/Weather-Cal#53]
I don’t know why but the weather stopped updating. And now is metric instead of imperial. I’ve tried “reset the widget”, “re enter the API key” and even deleted the script and installed it again but it still shows the same weather from 3 days ago.

Also, the other scripts I have work fine with the same API key. Is there some way to fix it? Thank you!

**Comment by mzeryck** [comment]
That is very odd! Can you copy this code into a new script, and tell me what happens when you run it? You may need to slide up to show the console:
```javascript
const fm = FileManager.local()
const path = fm.joinPath(fm.libraryDirectory(), "weather-cal-cache")
console.log(fm.modificationDate(path))
```

**Comment by ivyte** [comment]
It’s working now! Thank you so much
