### ISSUE TITLE
Weather error

### ISSUE THREAD

**Issue by anonym6373** [mzeryck/Weather-Cal#54]
Hi,

I have a problem with this widget because if I try to run the script or try to add it to my homescreen, i get the error message “undefined is not an object (evalating ‘weatherDataRaw.current.temp’) so I can’t use it. Please help my by fixing this error because I really want to use this widget without issues.
Thank you!

**Comment by anonym6373** [comment]
![7696DAB7-3A47-47B1-86C5-138E1A377E0A](https://user-images.githubusercontent.com/74816014/99874558-31ee3080-2be9-11eb-842f-689709b6e30d.png)

This is a preview of the issue.

**Comment by TheRealEvan584** [comment]
I had a similar issue when I first downloaded the widget too. Usually it has to do with your weather API. Make sure you typed in your API key correctly where it tells you to do so. If you just got your weather API key, it can take up to 24 hours for the key to activate so you might just have to wait.

**Comment by deroverda** [comment]
![Error after latest update](https://user-images.githubusercontent.com/70813982/99880633-ec475d00-2c14-11eb-838c-6649a253107b.jpeg)

**Comment by deroverda** [comment]
@mzeryck widget error after latest update.

**Comment by mzeryck** [comment]
@deroverda I believe I have fixed this, please run the update again and let me know if it works!

**Comment by deroverda** [comment]
> @deroverda I believe I have fixed this, please run the update again and let me know if it works!

Working! Thanks. What was the problem?

**Comment by mzeryck** [comment]
@deroverda It was basically a misalignment between the settings and the code. When you update, it doesn't overwrite your settings - but that means when new settings are added, they aren't added when you update. In this case, either the "covid" or "week" items were looking for their font settings and couldn't find them. The update makes sure the default font is used when those settings are missing.
