### ISSUE TITLE
Chance of Rain saying “NaN”

### ISSUE THREAD

**Issue by TheRealEvan584** [mzeryck/Weather-Cal#56]
I have the latest version of Weather Cal and I am unable to see the chance of rain. 
![8FAF195E-9A56-4553-B076-DA64F5383637](https://user-images.githubusercontent.com/73755743/99884963-ab911900-2bff-11eb-97ff-d530705b5622.png)

**Comment by mzeryck** [comment]
Thanks for submitting this, there were a few bugs in the weather data. If you run the update code, it should work now!

**Comment by TheRealEvan584** [comment]
It works now, thanks!
