### ISSUE TITLE
Forecast font size 

### ISSUE THREAD

**Issue by Stahl80** [mzeryck/Weather-Cal#60]
Is there a way to change to font size of the forecast? 

I changed for the current weather:
  largeTemp:   { size: 34, color: "", font: "light" },
    smallTemp:   { size: 12, color: "", font: "" },
    tinyTemp:    { size: 12, color: "", font: "" },

But I can’t find any setting for the forecast temperature.

**Comment by adamengineering** [comment]
The temperature for the forecast uses this

`tinyTemp: { size: 12, color: "", font: "" },`
