### ISSUE TITLE
Covid

### ISSUE THREAD

**Issue by Stahl80** [mzeryck/Weather-Cal#62]
Not so much an issue. But I was wondering if you would be able to add daily new cases for the COVID section. 

And thanks for all the work you put in to this 🙏

**Comment by caslan34** [comment]
Of course... go to code of Weather Cal, change code under localization 
`covid: "{todayCases} Cases, {todayDeaths} deaths, {active} Active" `

**Comment by Stahl80** [comment]
> Of course... go to code of Weather Cal, change code under localization 
> 
> `covid: "{todayCases} Cases, {todayDeaths} deaths, {active} Active" `

Thanks! 

Not sure how I missed that or if it was updated.

**Comment by caslan34** [comment]
No, this is code which I use... @mzeryck maybe he will put in code like options....

**Comment by mzeryck** [comment]
I will leave this issue open so I remember to document the available data types!

**Comment by mzeryck** [comment]
The newest update includes a list of all available {tokens}.
