### ISSUE TITLE
Open framework for third party functions

### ISSUE THREAD

**Issue by icsAT** [mzeryck/Weather-Cal#64]
Hello Max,

great script and good and well documented code. Actually I do not really have an issue. It's more a question or a request.

In a German Facebook group we had the request of displaying the Data Usage or to be more precise the Data left from your T-Mobile data plan. This is how I got pointed to your work. I took your source code from the Scriptable Gallery (wich is quite old) and quickly added the requested function.

Afterwards I checked your version on GitHub, that has some great improvements compared to the Gallery version.

Since this request is only interesting to Germans and even there, only to T-Mobile Germany customers, this is in my opinion no function to add to your base branch.
Also I have a second idea for Covid-19 data from German Robert-Koch Institute, since there is a lot of attention to this data in Germany. But again, it’s more something for Germans, than for the rest of the world.

Well, it’s no problem to add those functions to your script, but the problem is to stay up to date with your improvements then.

Have you ever thought about reading user provided additional functions from an other script/file?
So everyone could add the needed/wanted functionality without loosing the benefits of your improvements.
Do you see any chance for something like that?

Looking forward to your answer.

Greetings from Germany

Andre

**Comment by mzeryck** [comment]
Hi Andre, thanks so much for your request - it's actually something I had been working on for a while, and I'm really excited that it's finally ready! Please check out the [custom items section](https://github.com/mzeryck/Weather-Cal#custom-elements) of the readme file. Let me know if that makes sense, and please feel free to ask more questions, let me know about bugs, and share the custom items you're making!

**Comment by icsAT** [comment]
Hi Max, that sounds great. I will have a look at it. 
Actually I never was a fan of widgets on my homescreen, because it took to much space for all the wanted informations. Your widget changed that. I now have the possibillity to put everything I need into a medium widget. Great work. I haven't expected that you have a resolution for my request so fast. You surprised me. Thank you. I will come back to this topic as soon as I have tried it. And sure I will share my results.

This is what I had with your old code from Scriptable Gallery. I will try to rebuild that with your new custom items function.
![IMG_1255](https://user-images.githubusercontent.com/74063738/100517634-46ec3600-318c-11eb-8c33-ecab562a5008.jpeg)

**Comment by cutzenfriend** [comment]
@icsAT could you share your code? Greetings from Germany too ;)

**Comment by icsAT** [comment]
@cutzenfriend you find the script here:

https://gist.github.com/icsAT/208512f71232c03f22ea3c2aeda14d3a

But its based on the old version of Max's Script from Scriptable Gallery. I am working on moving this functions to Max's actual weather-cal.js. It's looking good so far. I will provide that modification too, as soon as it works.

**Comment by icsAT** [comment]
Hi Max (@mzeryck),

I could implement the items in the custom part of your script. It's running. The result (bottom) is almost the same as with the old (top) script:
![IMG_1270](https://user-images.githubusercontent.com/74063738/100528782-b55ae380-31e0-11eb-98a2-30cf708ffc3b.jpeg)

I was not sure, where to put the configuration part. I also used the custom section. Do you think that is alright?
So far I actually do not have any questions. Seems like you did a good job in explaining everything in your docs.

Here you will find my custom items:
https://gist.github.com/icsAT/1b832fa894fbe3fc1df99272c6ffd567

Greetings from Germany

Andre

**Comment by mzeryck** [comment]
This is really awesome, thank you Andre! Your configuration looks great to me - I have been planning to add a feature where custom items can add their own preferences. Also, I want to make the preferences themselves be exportable, so they're easier to share rather than taking screenshots (which is the only way right now!)

I am also planning to make a wiki page, and I'd love to have your gist linked there since you've done such a thorough job!

Very awesome!!

**Comment by icsAT** [comment]
Thanks Max,

I am looking foreward to the improvements of your script. Your ideas sound great. Feel free to link my gist on your wiki.
Just give me a hint if you need someone to test any of the custom features.

I will close this request here now, since there are no open points on it at the moment.

Greetings form Germany

Andre

**Comment by icsAT** [comment]
Wrong button, wanted to close it ;-)
