### ISSUE TITLE
Lowercase date 

### ISSUE THREAD

**Issue by sinusnode** [mzeryck/Weather-Cal#70]
Hi!
Is there a way to change the date format to make the first letter uppercase?
When I change the language to Spanish it  changes to lowercase and I’d like to have the same format as the English version if it’s possible 

Spanish
![DEC83A98-FDE0-40B3-850E-5845C67E2A3C](https://user-images.githubusercontent.com/75095308/100388536-7b2aef80-2ff0-11eb-961b-79b5c14ca129.jpeg)

English 
![A078EE46-0D86-4B7B-9E3A-BA24B44E95FF](https://user-images.githubusercontent.com/75095308/100388620-b7f6e680-2ff0-11eb-8d93-46b83861808e.jpeg)

Thank you!

**Comment by mzeryck** [comment]
Hi there, unfortunately there is not an easy way to do this. Scriptable uses the standard iOS region formats. You can see what your region looks like in the Settings app > General > Language & Region.
![IMG_0062](https://user-images.githubusercontent.com/71023727/100485605-8f84f000-30b5-11eb-9fed-d24e4c47a336.jpg)
If you are comfortable with Javascript, you could [override](https://github.com/mzeryck/Weather-Cal#custom-elements) the date function and make your own.
