### ISSUE TITLE
Error line 1342

### ISSUE THREAD

**Issue by suxus-zz** [mzeryck/Weather-Cal#71]
Hello

At the moment i have a error on

return (event.startDate.getTime() + minutesAfter > this.now.getTime())

Greeting
![IMG_1262](https://user-images.githubusercontent.com/17749132/100465125-14c8ce80-30cf-11eb-8071-f3acad12cdd1.jpeg)

**Comment by mzeryck** [comment]
Thank you for submitting this! I fixed a bug in both events and reminders that I hadn't caught in the new update. If you update the code again, it should work!
