### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by StratosHF** [mzeryck/Weather-Cal#72]
After a week of using the script just fine I’m having an error coming up after going through an area with no service. I’ve reset my phone, reset the script everything I k ow how to do to fix it but nothing. Figured id ask for help.
![1D356798-57EE-47DA-969C-F42DCBAD6D3B](https://user-images.githubusercontent.com/74522642/100482228-a717a500-30c4-11eb-8097-d7d675449734.png)

**Comment by StratosHF** [comment]
``

**Comment by mzeryck** [comment]
Hi there, this was a bug I accidentally introduced. It should be fixed now - try running Update code. (If doing that doesn't work, you might need to force-quit Scriptable and then run it again, I think it's caching stuff in the background.)

**Comment by StratosHF** [comment]
Thanks for your work!
