### ISSUE TITLE
Hourly forecast item

### ISSUE THREAD

**Issue by mzeryck** [mzeryck/Weather-Cal#74]
Create an "hourly" item that functions similarly to the "forecast" item, but instead shows upcoming hours of weather. Idea from [Eduardo](https://twitter.com/IamEduardoD/status/1332718016946184192) on Twitter.
- Change spacing setting to "Spacing between items", add description text
- Add a "Number of hours shown" setting
- Add a "Time format for hourly item" setting
- Build the method using "future" as the base

**Comment by seacatos** [comment]
Could you consider to display forecast and hourly in horizontal layout, please!

**Comment by mzeryck** [comment]
@seacatos These are both available in the newest update! You can add an "hourly" item to your layout, and you can set horizontal or vertical in the preferences editor!
