### ISSUE TITLE
Additional preferences on Widget Setup

### ISSUE THREAD

**Issue by ow410775** [mzeryck/Weather-Cal#75]
Could you please add below items as additional preferences as part of the Widget Setup?
- size of the icons (weather and battery)
- upper and lower cases of the texts (dates, greeting, etc.)

**Comment by mzeryck** [comment]
Making a note that I'm working on these - [Illustrious_Maybe_41](https://www.reddit.com/r/Scriptable/comments/k2q1u3/weather_cal_now_supports_custom_items_including/ge0byg4/?utm_source=reddit&utm_medium=web2x&context=3) also requested this on Reddit.

**Comment by mzeryck** [comment]
The most recent update adds support for text capitalization!
