### ISSUE TITLE
Run widget without internet

### ISSUE THREAD

**Issue by ow410775** [mzeryck/Weather-Cal#76]
Could you also make this widget run even if the phone is not connected on network/internet? If the widget has items that need network connection like weather -- it will not just display, or will display something like small line which will indicate that the particular feature/item needs network connection in order to display.

**Comment by mzeryck** [comment]
The widget now has minimum and maximum cache ages. This means if you lose connection for a short period of time, it will still show the widget items. If you lose connection for a long time, it will show a line or other indicator like you mentioned. Please try running "Update code" and seeing if this works better.
