### ISSUE TITLE
Error on line 769:51: TypeError: undefined is not an object (evaluating 'weatherDataRaw.current.temp')

### ISSUE THREAD

**Issue by hayashn** [mzeryck/Weather-Cal#78]
Error on line 769:51: TypeError: undefined is not an object (evaluating 'weatherDataRaw.current.temp')

**Comment by mzeryck** [comment]
Hi, this usually means your OpenWeather API key wasn't added, or it's new and hasn't activated yet. Could it be one of those two things?
