### ISSUE TITLE
Localised date format

### ISSUE THREAD

**Issue by FraserEmbrey** [mzeryck/Weather-Cal#82]
Is there a way to get the date and time to show in non-USA & 24hr format?

**Comment by mzeryck** [comment]
Yes! Run the script from the app to see the settings menu, then tap Edit preferences. There are two places to adjust things: in "Overall settings" you can set a specific [locale code](https://www.ibabbleon.com/iOS-Language-Codes-ISO-639.html) if the auto-detection isn't working. And then each item has its own [date format settings](https://docs.scriptable.app/dateformatter/) as well. Does that help?

**Comment by FraserEmbrey** [comment]
That's great, thank you very much.
