### ISSUE TITLE
Background transparent

### ISSUE THREAD

**Issue by Strassbauer** [mzeryck/Weather-Cal#90]
How can I set the background to transparent?

**Comment by TheRealEvan584** [comment]
First, you need to use a script called [Widget Blur](https://github.com/mzeryck/Widget-Blur/blob/main/widget-blur.js) which takes a portion of your wallpaper which you can then use as a background for a widget. Once you have created an image with [Widget Blur](https://github.com/mzeryck/Widget-Blur/blob/main/widget-blur.js), you can use that image as the background of Weather Cal. To reset the background of your Weather Cal Widget you can click on the script and click “Change Background”.

**Comment by Strassbauer** [comment]
Thanks it works 👍🏽
