### ISSUE TITLE
Calendar setting

### ISSUE THREAD

**Issue by Roquer77** [mzeryck/Weather-Cal#91]
Hello!
How do I get the script only to show one specific calendar of mine? I tried some things like a public google calenderadress, my private google calendaradress, my iPhone calender names and so on. Nothing worked. Can you tell what I have to do to that the script only shows my personal google calendar? Thanks for your help.

**Comment by mzeryck** [comment]
Sure thing! First, you do need to have the exact names of each calendar within the iPhone Calendar app. Then go to the setup menu > Edit preferences > Events > Calendars to show. Here, you need to list them with commas but no spaces, like this: Personal,Work,Family

**Comment by Roquer77** [comment]
Thanks a lot for your quick answer. Sadly it does not work. I don't know if this is because I'm working with a google calender that is imported into my iPhone calendar. Any ideas?

**Comment by adamengineering** [comment]
You have to write it like this

["Personal","Work","Family"] and the names must correspond to those in the calendar app

**Comment by LTLNEMO** [comment]
On a sidenote relating to calendar events. Mine aren't showing. Set future to 7. Just seeings the default message. Does it take a while for the widget to refresh?

**Comment by LTLNEMO** [comment]
Never mind. I had to change the 20 to 0 to always show.

But now I don't want the date to revert to small and always want it large. How do I do that

**Comment by mzeryck** [comment]
@Roquer77 Would you be OK sharing the calendar names here? There are some situations where this may not work - for example, if two calendars have the same name.

**Comment by Roquer77** [comment]
Hi, sorry that I let you wait.

Sure, it's no problem for me.
The calendarnames (as they are shown in my apple calendar app are:
Jens
Evy

**Comment by icsAT** [comment]
@Roquer77,

usually it should work if you put the one you want to see in the "Calendars to show" like @mzeryck described. Did you try both of them on their own? Is at least one of them working? Also check if you f.e. have a space in the iOS calendar name in front of or after the name. I had a problem with a trailing space in the iOS calendar name a few days ago.

@mzeryck I did not really look into the code how you select the events from the calendars, but is it possible to trim each item of "selectCalendars" and also trim the names of the iOS Calendars while selecting the events?

Greetings Andre

**Comment by Roquer77** [comment]
> @Roquer77,
> 
> 
> 
> usually it should work if you put the one you want to see in the "Calendars to show" like @mzeryck described. Did you try both of them on their own? Is at least one of them working? Also check if you f.e. have a space in the iOS calendar name in front of or after the name. I had a problem with a trailing space in the iOS calendar name a few days ago.
> 
> 
> 
> @mzeryck I did not really look into the code how you select the events from the calendars, but is it possible to trim each item of "selectCalendars" and also trim the names of the iOS Calendars while selecting the events?
> 
> 
> 
> Greetings Andre

Hey Andre, thank you for the reply.
Indeed I tried every calendar on its own. The result is always the same: Ir shows every calendar.

**Comment by mzeryck** [comment]
@Roquer77 Hi there, thanks for providing more detail! The "Awaiting" badge is just to note that the issue needs more detail before I can work on it. But it stayed up even as I took a few days off from working on this project. I have some more time finally to look into this!

@icsAT I think you may be on the right track - I have been thinking about rewriting calendar selection since it is very rudimentary.

**Comment by Roquer77** [comment]
> @Roquer77 Hi there, thanks for providing more detail! The "Awaiting" badge is just to note that the issue needs more detail before I can work on it. But it stayed up even as I took a few days off from working on this project. I have some more time finally to look into this!
> 
> 
> 
> @icsAT I think you may be on the right track - I have been thinking about rewriting calendar selection since it is very rudimentary.

No problem for me. I must say that coding is not a profession of mine so that I'm doing my best to get things work while I try to understand how these codes work. So while I'm on duty I'll just be patient waitimg for pros like you that can figure out the issue. No need to hurry on this project and no need for an excuse or something. I'm just happy that there are people who are working on these scripts and hand it out here. Thank you!

**Comment by mzeryck** [comment]
@Roquer77 Hello, please try the newest update to Weather Cal: first, run "Update code", and then "Edit preferences". When you tap on "Calendars to show" it will now display a list of the available calendars. Tap on the calendar you want to select it. 

This view uses the calendar identifiers, rather than the titles. So, it should be more accurate! Please try it out and let me know if it fixes the issue!

**Comment by Roquer77** [comment]
> @Roquer77 Hello, please try the newest update to Weather Cal: first, run "Update code", and then "Edit preferences". When you tap on "Calendars to show" it will now display a list of the available calendars. Tap on the calendar you want to select it. 
> 
> 
> 
> This view uses the calendar identifiers, rather than the titles. So, it should be more accurate! Please try it out and let me know if it fixes the issue!

Hi!
It works! I'm sorry for answering late but here in germany we celebrate christmas on the 24th. On top I've gotta work a 24 hrs shift. Everytime I got some sparetime I tried to update the code. I deletet it completely and used the code from script dude. This works absolutely fine and in the way I would expect it. Thabk you again for your work and passion you put into it. I hope you have a merry christmas with your belobed ones!
Greets

Jens
