### ISSUE TITLE
Some help please 

### ISSUE THREAD

**Issue by musmer** [mzeryck/Weather-Cal#94]
![F8226A05-D75F-4F02-9E80-E18D2840794C](https://user-images.githubusercontent.com/76070149/102265432-65d22280-3f17-11eb-9d14-fdc6d715817e.png)
![Uploading 31FFAF77-E203-4091-80C7-DB168448BFE7.png…]()

**Comment by addyire** [comment]
Im having the same problem

**Comment by addyire** [comment]
Fixed by using another script that requires location like iTermWidget which then prompts for location access.
Then deleting "Weather Cal(or whatever you name it) code" then re-running the start script.

**Comment by mzeryck** [comment]
@musmer @addyire Really sorry about this - pushed out a bug. Please force-quit Scriptable, delete the "Weather Cal code" script, and then re-run the widget script.
