### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ARashkind** [mzeryck/Weather-Cal#96]
I am really enjoying Weather Cal. I have it running on my iPhone and iPad. Almost all of my information I need is viewable from the Large Widget. I have a couple requests as I have tried to get it working through coding, but wasn't able to make it work exactly.

1. Is there a way to allow the Sunrise, Sunset, and Battery items to take up only one line? Right now, it takes up three separate lines. I tried creating this look with columns, but it didn't work well.

2. Is there a way to add Stocks into the widget. I was able to embed a Stock Widget into the Weather Cal widget, but it takes up too much space. Is there a way to have it just take up a line like the COVID information?

**Comment by icsAT** [comment]
@ARashkind,

The answer to number one is easy:
Just add a row with three column(s) to your layout, where you place those items.
row
   column
      battery
   column
      sunrise
   column
      sunset

**Comment by ARashkind** [comment]
Thanks for the quick reply. I had tried that, but the spacing of the columns didn't look right. Wasn't sure if there was a way to have it all on one column instead.

**Comment by icsAT** [comment]
You are able to do something like that:

row
column
left
battery
column
center
sunrise
column
right
sunset

I dont know what you are expecting exactly, so its hard to help.
You also could try to use space and/or set the size of the column(100) like that. I think almost ervery look is possible.
