### ISSUE TITLE
Message Stack error

### ISSUE THREAD

**Issue by admartinezjr** [mzeryck/Weather-Cal#97]
New error since last night. MessageStack
It happens every time the widget refreshes. 

![F9088BCB-7F33-4CB8-8A04-A07078AA4810](https://user-images.githubusercontent.com/76121626/102381876-c3a64f00-3f97-11eb-8ce1-ac9d8ec9b8d1.png)

**Comment by icsAT** [comment]
@admartinezjr I think there really might be a problem in the code if there are no reminders. @mzeryck removed some code 2 days ago including the messageStack. I am not sure if it should be named reminderStack now, but you found the on line where there is still an messageStack.

Greetings Andre

**Comment by admartinezjr** [comment]
Hi Andre, thanks for the reply. It does seem to happen when all the reminders are done, now that you mentioned this. Hopefully it can be fixed in an update soon. The widget is unusable once this happens.

**Comment by admartinezjr** [comment]
In the meantime, turning off the “message” for no reminders, fixes it. Hoping for a permanent fix soon.

**Comment by mzeryck** [comment]
@admartinezjr Sorry about that! I've fixed the bug, updating should fix the issue!

**Comment by admartinezjr** [comment]
Thanks @mzeryck. Appreciate it!
